/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner } from './GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner';
import {
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSON,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSON,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner';
import type { GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner } from './GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner';
import {
    GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerFromJSON,
    GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerToJSON,
    GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner';
import type { GetAllAsync200ResponseItemsInnerQuotePolicy } from './GetAllAsync200ResponseItemsInnerQuotePolicy';
import {
    GetAllAsync200ResponseItemsInnerQuotePolicyFromJSON,
    GetAllAsync200ResponseItemsInnerQuotePolicyFromJSONTyped,
    GetAllAsync200ResponseItemsInnerQuotePolicyToJSON,
    GetAllAsync200ResponseItemsInnerQuotePolicyToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerQuotePolicy';
import type { GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInner } from './GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInner';
import {
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerFromJSON,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerToJSON,
    GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInner';

/**
 * Quote information related to the Booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerQuote
 */
export interface GetAllAsync200ResponseItemsInnerQuote {
    /**
     * Id of the Quote
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    id?: number;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerQuotePolicy}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    policy?: GetAllAsync200ResponseItemsInnerQuotePolicy;
    /**
     * Information about the quote status
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    status?: GetAllAsync200ResponseItemsInnerQuoteStatusEnum;
    /**
     * Schedule details enforced by the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    scheduledTransactions?: Array<GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner> | null;
    /**
     * Schedule details of damage protection enforced by the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    scheduledDamageProtection?: Array<GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInner> | null;
    /**
     * Room types belonging to the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    roomTypeItems?: Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInner> | null;
    /**
     * Addons belonging to the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    addonItems?: Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner> | null;
    /**
     * Other items belonging to the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    otherItems?: Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner> | null;
    /**
     * Vat items belonging to the Quote
     * @type {Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner>}
     * @memberof GetAllAsync200ResponseItemsInnerQuote
     */
    vatItems?: Array<GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner> | null;
}


/**
 * @export
 */
export const GetAllAsync200ResponseItemsInnerQuoteStatusEnum = {
    Null: 'Null',
    NotScheduled: 'NotScheduled',
    NotSent: 'NotSent',
    Agreed: 'Agreed',
    CancelledByOwner: 'CancelledByOwner',
    CancelledByGuest: 'CancelledByGuest',
    Rejected: 'Rejected',
    Deactivated: 'Deactivated',
    ExpiredByGuest: 'ExpiredByGuest',
    ExpiredByOwner: 'ExpiredByOwner',
    PendingForOwner: 'PendingForOwner',
    PendingForGuest: 'PendingForGuest',
    PendingForPayment: 'PendingForPayment',
    RedirectedToOffsitePayment: 'RedirectedToOffsitePayment',
    ChangeRequested: 'ChangeRequested',
    Changed: 'Changed',
    Disconnected: 'Disconnected'
} as const;
export type GetAllAsync200ResponseItemsInnerQuoteStatusEnum = typeof GetAllAsync200ResponseItemsInnerQuoteStatusEnum[keyof typeof GetAllAsync200ResponseItemsInnerQuoteStatusEnum];


/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerQuote interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerQuote(value: object): value is GetAllAsync200ResponseItemsInnerQuote {
    return true;
}

export function GetAllAsync200ResponseItemsInnerQuoteFromJSON(json: any): GetAllAsync200ResponseItemsInnerQuote {
    return GetAllAsync200ResponseItemsInnerQuoteFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'policy': json['policy'] == null ? undefined : GetAllAsync200ResponseItemsInnerQuotePolicyFromJSON(json['policy']),
        'status': json['status'] == null ? undefined : json['status'],
        'scheduledTransactions': json['scheduled_transactions'] == null ? undefined : ((json['scheduled_transactions'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerFromJSON)),
        'scheduledDamageProtection': json['scheduled_damage_protection'] == null ? undefined : ((json['scheduled_damage_protection'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerFromJSON)),
        'roomTypeItems': json['room_type_items'] == null ? undefined : ((json['room_type_items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerFromJSON)),
        'addonItems': json['addon_items'] == null ? undefined : ((json['addon_items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSON)),
        'otherItems': json['other_items'] == null ? undefined : ((json['other_items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSON)),
        'vatItems': json['vat_items'] == null ? undefined : ((json['vat_items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSON)),
    };
}

export function GetAllAsync200ResponseItemsInnerQuoteToJSON(json: any): GetAllAsync200ResponseItemsInnerQuote {
    return GetAllAsync200ResponseItemsInnerQuoteToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerQuoteToJSONTyped(value?: GetAllAsync200ResponseItemsInnerQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'policy': GetAllAsync200ResponseItemsInnerQuotePolicyToJSON(value['policy']),
        'status': value['status'],
        'scheduled_transactions': value['scheduledTransactions'] == null ? undefined : ((value['scheduledTransactions'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerToJSON)),
        'scheduled_damage_protection': value['scheduledDamageProtection'] == null ? undefined : ((value['scheduledDamageProtection'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteScheduledTransactionsInnerToJSON)),
        'room_type_items': value['roomTypeItems'] == null ? undefined : ((value['roomTypeItems'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerToJSON)),
        'addon_items': value['addonItems'] == null ? undefined : ((value['addonItems'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSON)),
        'other_items': value['otherItems'] == null ? undefined : ((value['otherItems'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSON)),
        'vat_items': value['vatItems'] == null ? undefined : ((value['vatItems'] as Array<any>).map(GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSON)),
    };
}

