/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents check-out for a booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerCheckOut
 */
export interface GetAllAsync200ResponseItemsInnerCheckOut {
    /**
     * The check-out time
     * Format: HH:mm:ss
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerCheckOut
     */
    time?: string | null;
    /**
     * The check-out source of change
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerCheckOut
     */
    initiator?: string | null;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerCheckOut interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerCheckOut(value: object): value is GetAllAsync200ResponseItemsInnerCheckOut {
    return true;
}

export function GetAllAsync200ResponseItemsInnerCheckOutFromJSON(json: any): GetAllAsync200ResponseItemsInnerCheckOut {
    return GetAllAsync200ResponseItemsInnerCheckOutFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerCheckOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerCheckOut {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'initiator': json['initiator'] == null ? undefined : json['initiator'],
    };
}

export function GetAllAsync200ResponseItemsInnerCheckOutToJSON(json: any): GetAllAsync200ResponseItemsInnerCheckOut {
    return GetAllAsync200ResponseItemsInnerCheckOutToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerCheckOutToJSONTyped(value?: GetAllAsync200ResponseItemsInnerCheckOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'initiator': value['initiator'],
    };
}

