/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner
 */
export interface GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner {
    /**
     * Quote item type
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner
     */
    type?: string | null;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner
     */
    amount?: object;
    /**
     * Quote item description
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner
     */
    description?: string | null;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner(value: object): value is GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner {
    return true;
}

export function GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSON(json: any): GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner {
    return GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSON(json: any): GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner {
    return GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInnerToJSONTyped(value?: GetAllAsync200ResponseItemsInnerQuoteRoomTypeItemsInnerPricesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

