/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents check-in for a booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerCheckIn
 */
export interface GetAllAsync200ResponseItemsInnerCheckIn {
    /**
     * The check-in time
     * Format: HH:mm:ss
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerCheckIn
     */
    time?: string | null;
    /**
     * The check-in source of change
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerCheckIn
     */
    initiator?: string | null;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerCheckIn interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerCheckIn(value: object): value is GetAllAsync200ResponseItemsInnerCheckIn {
    return true;
}

export function GetAllAsync200ResponseItemsInnerCheckInFromJSON(json: any): GetAllAsync200ResponseItemsInnerCheckIn {
    return GetAllAsync200ResponseItemsInnerCheckInFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerCheckInFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerCheckIn {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'initiator': json['initiator'] == null ? undefined : json['initiator'],
    };
}

export function GetAllAsync200ResponseItemsInnerCheckInToJSON(json: any): GetAllAsync200ResponseItemsInnerCheckIn {
    return GetAllAsync200ResponseItemsInnerCheckInToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerCheckInToJSONTyped(value?: GetAllAsync200ResponseItemsInnerCheckIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'initiator': value['initiator'],
    };
}

