/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Guest breakdown
 * @export
 * @interface GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown
 */
export interface GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown {
    /**
     * Number of adults
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown
     */
    adults?: number;
    /**
     * Number of children
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown
     */
    children?: number;
    /**
     * Number of infants
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown
     */
    infants?: number;
    /**
     * Number of pets
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown
     */
    pets?: number;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown(value: object): value is GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown {
    return true;
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON(json: any): GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown {
    return GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'adults': json['adults'] == null ? undefined : json['adults'],
        'children': json['children'] == null ? undefined : json['children'],
        'infants': json['infants'] == null ? undefined : json['infants'],
        'pets': json['pets'] == null ? undefined : json['pets'],
    };
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON(json: any): GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown {
    return GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSONTyped(value?: GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adults': value['adults'],
        'children': value['children'],
        'infants': value['infants'],
        'pets': value['pets'],
    };
}

