/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod
 */
export interface GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod {
    /**
     * 
     * @type {number}
     * @memberof GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod
     */
    id?: number;
}

/**
 * Check if a given object implements the GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod interface.
 */
export function instanceOfGetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod(value: object): value is GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod {
    return true;
}

export function GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSON(json: any): GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod {
    return GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSONTyped(json, false);
}

export function GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSON(json: any): GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod {
    return GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSONTyped(json, false);
}

export function GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSONTyped(value?: GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

