/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * External booking model
 * @export
 * @interface GetExternalBookingsAsync200ResponseExternalBookingsInner
 */
export interface GetExternalBookingsAsync200ResponseExternalBookingsInner {
    /**
     * Time the external booking was created at
     * @type {Date}
     * @memberof GetExternalBookingsAsync200ResponseExternalBookingsInner
     */
    createdAt?: Date;
    /**
     * Contents of the external booking
     * @type {string}
     * @memberof GetExternalBookingsAsync200ResponseExternalBookingsInner
     */
    content?: string | null;
}

/**
 * Check if a given object implements the GetExternalBookingsAsync200ResponseExternalBookingsInner interface.
 */
export function instanceOfGetExternalBookingsAsync200ResponseExternalBookingsInner(value: object): value is GetExternalBookingsAsync200ResponseExternalBookingsInner {
    return true;
}

export function GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSON(json: any): GetExternalBookingsAsync200ResponseExternalBookingsInner {
    return GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSONTyped(json, false);
}

export function GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExternalBookingsAsync200ResponseExternalBookingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSON(json: any): GetExternalBookingsAsync200ResponseExternalBookingsInner {
    return GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSONTyped(json, false);
}

export function GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSONTyped(value?: GetExternalBookingsAsync200ResponseExternalBookingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'content': value['content'],
    };
}

