/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a payment link for a booking
 * @export
 * @interface GetPaymentLinkAsync200Response
 */
export interface GetPaymentLinkAsync200Response {
    /**
     * Url address to the payment page
     * @type {string}
     * @memberof GetPaymentLinkAsync200Response
     */
    url?: string | null;
}

/**
 * Check if a given object implements the GetPaymentLinkAsync200Response interface.
 */
export function instanceOfGetPaymentLinkAsync200Response(value: object): value is GetPaymentLinkAsync200Response {
    return true;
}

export function GetPaymentLinkAsync200ResponseFromJSON(json: any): GetPaymentLinkAsync200Response {
    return GetPaymentLinkAsync200ResponseFromJSONTyped(json, false);
}

export function GetPaymentLinkAsync200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentLinkAsync200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetPaymentLinkAsync200ResponseToJSON(json: any): GetPaymentLinkAsync200Response {
    return GetPaymentLinkAsync200ResponseToJSONTyped(json, false);
}

export function GetPaymentLinkAsync200ResponseToJSONTyped(value?: GetPaymentLinkAsync200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

