/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Policy information related to the Booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto {
    /**
     * Name of the policy
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto
     */
    name?: string | null;
    /**
     * Description of the payment policy
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto
     */
    payments?: string | null;
    /**
     * Description of the cancellation policy
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto
     */
    cancellation?: string | null;
    /**
     * Description of the damage deposit policy
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto
     */
    damageDeposit?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'payments': json['payments'] == null ? undefined : json['payments'],
        'cancellation': json['cancellation'] == null ? undefined : json['cancellation'],
        'damageDeposit': json['damage_deposit'] == null ? undefined : json['damage_deposit'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsQuotesPolicyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'payments': value['payments'],
        'cancellation': value['cancellation'],
        'damage_deposit': value['damageDeposit'],
    };
}

