/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the amount to be paid through the website
 * @export
 * @interface LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto
 */
export interface LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto {
    /**
     * Amount to request
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto
     */
    amount?: number;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto(value: object): value is LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto {
    return LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto {
    return LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV12CreatePaymentLinkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

