/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInnerCheckIn } from './GetAllAsync200ResponseItemsInnerCheckIn';
import {
    GetAllAsync200ResponseItemsInnerCheckInFromJSON,
    GetAllAsync200ResponseItemsInnerCheckInFromJSONTyped,
    GetAllAsync200ResponseItemsInnerCheckInToJSON,
    GetAllAsync200ResponseItemsInnerCheckInToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerCheckIn';
import type { GetAllAsync200ResponseItemsInnerTransactionsInner } from './GetAllAsync200ResponseItemsInnerTransactionsInner';
import {
    GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSON,
    GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerTransactionsInnerToJSON,
    GetAllAsync200ResponseItemsInnerTransactionsInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerTransactionsInner';
import type { GetAllAsync200ResponseItemsInnerGuest } from './GetAllAsync200ResponseItemsInnerGuest';
import {
    GetAllAsync200ResponseItemsInnerGuestFromJSON,
    GetAllAsync200ResponseItemsInnerGuestFromJSONTyped,
    GetAllAsync200ResponseItemsInnerGuestToJSON,
    GetAllAsync200ResponseItemsInnerGuestToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerGuest';
import type { GetAllAsync200ResponseItemsInnerQuote } from './GetAllAsync200ResponseItemsInnerQuote';
import {
    GetAllAsync200ResponseItemsInnerQuoteFromJSON,
    GetAllAsync200ResponseItemsInnerQuoteFromJSONTyped,
    GetAllAsync200ResponseItemsInnerQuoteToJSON,
    GetAllAsync200ResponseItemsInnerQuoteToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerQuote';
import type { GetAllAsync200ResponseItemsInnerCheckOut } from './GetAllAsync200ResponseItemsInnerCheckOut';
import {
    GetAllAsync200ResponseItemsInnerCheckOutFromJSON,
    GetAllAsync200ResponseItemsInnerCheckOutFromJSONTyped,
    GetAllAsync200ResponseItemsInnerCheckOutToJSON,
    GetAllAsync200ResponseItemsInnerCheckOutToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerCheckOut';
import type { GetAllAsync200ResponseItemsInnerRoomsInner } from './GetAllAsync200ResponseItemsInnerRoomsInner';
import {
    GetAllAsync200ResponseItemsInnerRoomsInnerFromJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerRoomsInnerToJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerRoomsInner';
import type { GetAllAsync200ResponseItemsInnerSubtotals } from './GetAllAsync200ResponseItemsInnerSubtotals';
import {
    GetAllAsync200ResponseItemsInnerSubtotalsFromJSON,
    GetAllAsync200ResponseItemsInnerSubtotalsFromJSONTyped,
    GetAllAsync200ResponseItemsInnerSubtotalsToJSON,
    GetAllAsync200ResponseItemsInnerSubtotalsToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerSubtotals';

/**
 * Main booking model
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto {
    /**
     * Id of the booking
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    id?: number;
    /**
     * User the booking belongs to
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    userId?: number;
    /**
     * Arrival date
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    arrival?: string;
    /**
     * Departure date
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    departure?: string;
    /**
     * Id of the property
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    propertyId?: number;
    /**
     * Rooms booked
     * @type {Array<GetAllAsync200ResponseItemsInnerRoomsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    rooms?: Array<GetAllAsync200ResponseItemsInnerRoomsInner> | null;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerGuest}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    guest?: GetAllAsync200ResponseItemsInnerGuest;
    /**
     * Language selected by the guest
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    language?: string | null;
    /**
     * Status information of the Booking
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    status?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoStatusEnum;
    /**
     * Booking cannot be booked because calendar is not available
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    isUnavailable?: boolean;
    /**
     * Booking is overbooked
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    isOverbooked?: boolean;
    /**
     * Time the Tentative status will expire at
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    tentativeExpiresAt?: Date | null;
    /**
     * Type of source the Booking comes from
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    source?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoSourceEnum;
    /**
     * Details of the booking from the source
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    sourceText?: string | null;
    /**
     * Ip the booking was created from
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    createdFromIp?: string | null;
    /**
     * Time the booking was created at
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    createdAt?: Date;
    /**
     * Last time the booking was updated
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    updatedAt?: Date;
    /**
     * Date the booking was canceled at
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    canceledAt?: Date | null;
    /**
     * When it is new, the owner has not seen the booking yet
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    isNew?: boolean;
    /**
     * When it is deleted, the owner moved the booking to trash
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    isDeleted?: boolean;
    /**
     * Currency in which all amounts are expressed for this booking
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    currencyCode?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    totalAmount?: object;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerSubtotals}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    subtotals?: GetAllAsync200ResponseItemsInnerSubtotals;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    amountPaid?: object;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    amountDue?: object;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerQuote}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    quote?: GetAllAsync200ResponseItemsInnerQuote;
    /**
     * Transaction details of the booking
     * @type {Array<GetAllAsync200ResponseItemsInnerTransactionsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    transactions?: Array<GetAllAsync200ResponseItemsInnerTransactionsInner> | null;
    /**
     * Damage-protection transaction details of the booking
     * @type {Array<GetAllAsync200ResponseItemsInnerTransactionsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    damageProtection?: Array<GetAllAsync200ResponseItemsInnerTransactionsInner> | null;
    /**
     * Notes added by the owner
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    notes?: string | null;
    /**
     * Uid of the message thread the booking belongs to
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    threadUid?: string;
    /**
     * Booking information as received from an external channel
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    externalBooking?: string | null;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerCheckIn}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    checkIn?: GetAllAsync200ResponseItemsInnerCheckIn;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerCheckOut}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto
     */
    checkOut?: GetAllAsync200ResponseItemsInnerCheckOut;
}


/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoStatusEnum = {
    Open: 'Open',
    Tentative: 'Tentative',
    Booked: 'Booked',
    Declined: 'Declined'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoStatusEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoStatusEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoStatusEnum];

/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoSourceEnum = {
    Manual: 'Manual',
    Oh: 'OH',
    NineFlats: 'NineFlats',
    Airbnb: 'Airbnb',
    AirbnbIntegration: 'AirbnbIntegration',
    HomeAway: 'HomeAway',
    BookingCom: 'BookingCom',
    Expedia: 'Expedia',
    ICal: 'ICal',
    Email: 'Email',
    FacebookMessenger: 'FacebookMessenger',
    PublicApi: 'PublicApi',
    Other: 'Other'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoSourceEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoSourceEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoSourceEnum];


/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'arrival': json['arrival'] == null ? undefined : json['arrival'],
        'departure': json['departure'] == null ? undefined : json['departure'],
        'propertyId': json['property_id'] == null ? undefined : json['property_id'],
        'rooms': json['rooms'] == null ? undefined : ((json['rooms'] as Array<any>).map(GetAllAsync200ResponseItemsInnerRoomsInnerFromJSON)),
        'guest': json['guest'] == null ? undefined : GetAllAsync200ResponseItemsInnerGuestFromJSON(json['guest']),
        'language': json['language'] == null ? undefined : json['language'],
        'status': json['status'] == null ? undefined : json['status'],
        'isUnavailable': json['is_unavailable'] == null ? undefined : json['is_unavailable'],
        'isOverbooked': json['is_overbooked'] == null ? undefined : json['is_overbooked'],
        'tentativeExpiresAt': json['tentative_expires_at'] == null ? undefined : (new Date(json['tentative_expires_at'])),
        'source': json['source'] == null ? undefined : json['source'],
        'sourceText': json['source_text'] == null ? undefined : json['source_text'],
        'createdFromIp': json['created_from_ip'] == null ? undefined : json['created_from_ip'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'canceledAt': json['canceled_at'] == null ? undefined : (new Date(json['canceled_at'])),
        'isNew': json['is_new'] == null ? undefined : json['is_new'],
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
        'subtotals': json['subtotals'] == null ? undefined : GetAllAsync200ResponseItemsInnerSubtotalsFromJSON(json['subtotals']),
        'amountPaid': json['amount_paid'] == null ? undefined : json['amount_paid'],
        'amountDue': json['amount_due'] == null ? undefined : json['amount_due'],
        'quote': json['quote'] == null ? undefined : GetAllAsync200ResponseItemsInnerQuoteFromJSON(json['quote']),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSON)),
        'damageProtection': json['damage_protection'] == null ? undefined : ((json['damage_protection'] as Array<any>).map(GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'threadUid': json['thread_uid'] == null ? undefined : json['thread_uid'],
        'externalBooking': json['external_booking'] == null ? undefined : json['external_booking'],
        'checkIn': json['check_in'] == null ? undefined : GetAllAsync200ResponseItemsInnerCheckInFromJSON(json['check_in']),
        'checkOut': json['check_out'] == null ? undefined : GetAllAsync200ResponseItemsInnerCheckOutFromJSON(json['check_out']),
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'arrival': value['arrival'],
        'departure': value['departure'],
        'property_id': value['propertyId'],
        'rooms': value['rooms'] == null ? undefined : ((value['rooms'] as Array<any>).map(GetAllAsync200ResponseItemsInnerRoomsInnerToJSON)),
        'guest': GetAllAsync200ResponseItemsInnerGuestToJSON(value['guest']),
        'language': value['language'],
        'status': value['status'],
        'is_unavailable': value['isUnavailable'],
        'is_overbooked': value['isOverbooked'],
        'tentative_expires_at': value['tentativeExpiresAt'] == null ? undefined : ((value['tentativeExpiresAt'] as any).toISOString()),
        'source': value['source'],
        'source_text': value['sourceText'],
        'created_from_ip': value['createdFromIp'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'canceled_at': value['canceledAt'] == null ? undefined : ((value['canceledAt'] as any).toISOString()),
        'is_new': value['isNew'],
        'is_deleted': value['isDeleted'],
        'currency_code': value['currencyCode'],
        'total_amount': value['totalAmount'],
        'subtotals': GetAllAsync200ResponseItemsInnerSubtotalsToJSON(value['subtotals']),
        'amount_paid': value['amountPaid'],
        'amount_due': value['amountDue'],
        'quote': GetAllAsync200ResponseItemsInnerQuoteToJSON(value['quote']),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(GetAllAsync200ResponseItemsInnerTransactionsInnerToJSON)),
        'damage_protection': value['damageProtection'] == null ? undefined : ((value['damageProtection'] as Array<any>).map(GetAllAsync200ResponseItemsInnerTransactionsInnerToJSON)),
        'notes': value['notes'],
        'thread_uid': value['threadUid'],
        'external_booking': value['externalBooking'],
        'check_in': GetAllAsync200ResponseItemsInnerCheckInToJSON(value['checkIn']),
        'check_out': GetAllAsync200ResponseItemsInnerCheckOutToJSON(value['checkOut']),
    };
}

