/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInner } from './GetAllAsync200ResponseItemsInner';
import {
    GetAllAsync200ResponseItemsInnerFromJSON,
    GetAllAsync200ResponseItemsInnerFromJSONTyped,
    GetAllAsync200ResponseItemsInnerToJSON,
    GetAllAsync200ResponseItemsInnerToJSONTyped,
} from './GetAllAsync200ResponseItemsInner';

/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto {
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto
     */
    count?: number | null;
    /**
     * 
     * @type {Array<GetAllAsync200ResponseItemsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto
     */
    items?: Array<GetAllAsync200ResponseItemsInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerFromJSON)),
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingSetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(GetAllAsync200ResponseItemsInnerToJSON)),
    };
}

