/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseCalendarItemsInnerPricesInner } from './RatesCalendarV2200ResponseCalendarItemsInnerPricesInner';
import {
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSONTyped,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseCalendarItemsInnerPricesInner';

/**
 * 
 * @export
 * @interface LodgifyApiRatesModelsV2CalendarResponseItem
 */
export interface LodgifyApiRatesModelsV2CalendarResponseItem {
    /**
     * Represents the DateTime for the calendar item
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2CalendarResponseItem
     */
    date?: string | null;
    /**
     * Indicates if the calendar item is the default rate
     * @type {boolean}
     * @memberof LodgifyApiRatesModelsV2CalendarResponseItem
     */
    isDefault?: boolean;
    /**
     * List of prices for the calendar item
     * @type {Array<RatesCalendarV2200ResponseCalendarItemsInnerPricesInner>}
     * @memberof LodgifyApiRatesModelsV2CalendarResponseItem
     */
    prices?: Array<RatesCalendarV2200ResponseCalendarItemsInnerPricesInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2CalendarResponseItem interface.
 */
export function instanceOfLodgifyApiRatesModelsV2CalendarResponseItem(value: object): value is LodgifyApiRatesModelsV2CalendarResponseItem {
    return true;
}

export function LodgifyApiRatesModelsV2CalendarResponseItemFromJSON(json: any): LodgifyApiRatesModelsV2CalendarResponseItem {
    return LodgifyApiRatesModelsV2CalendarResponseItemFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2CalendarResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'prices': json['prices'] == null ? undefined : ((json['prices'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSON)),
    };
}

export function LodgifyApiRatesModelsV2CalendarResponseItemToJSON(json: any): LodgifyApiRatesModelsV2CalendarResponseItem {
    return LodgifyApiRatesModelsV2CalendarResponseItemToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarResponseItemToJSONTyped(value?: LodgifyApiRatesModelsV2CalendarResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'is_default': value['isDefault'],
        'prices': value['prices'] == null ? undefined : ((value['prices'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSON)),
    };
}

