/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiRatesModelsV2CalendarPrice
 */
export interface LodgifyApiRatesModelsV2CalendarPrice {
    /**
     * Minimum days to stay
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2CalendarPrice
     */
    minStay?: number;
    /**
     * Maximum days to stay
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2CalendarPrice
     */
    maxStay?: number;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiRatesModelsV2CalendarPrice
     */
    pricePerDay?: object;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiRatesModelsV2CalendarPrice
     */
    pricePerAdditionalGuest?: object;
    /**
     * Indicates the number of people from which an extra charge is charged
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2CalendarPrice
     */
    additionalGuestsStartsFrom?: number;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2CalendarPrice interface.
 */
export function instanceOfLodgifyApiRatesModelsV2CalendarPrice(value: object): value is LodgifyApiRatesModelsV2CalendarPrice {
    return true;
}

export function LodgifyApiRatesModelsV2CalendarPriceFromJSON(json: any): LodgifyApiRatesModelsV2CalendarPrice {
    return LodgifyApiRatesModelsV2CalendarPriceFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2CalendarPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'minStay': json['min_stay'] == null ? undefined : json['min_stay'],
        'maxStay': json['max_stay'] == null ? undefined : json['max_stay'],
        'pricePerDay': json['price_per_day'] == null ? undefined : json['price_per_day'],
        'pricePerAdditionalGuest': json['price_per_additional_guest'] == null ? undefined : json['price_per_additional_guest'],
        'additionalGuestsStartsFrom': json['additional_guests_starts_from'] == null ? undefined : json['additional_guests_starts_from'],
    };
}

export function LodgifyApiRatesModelsV2CalendarPriceToJSON(json: any): LodgifyApiRatesModelsV2CalendarPrice {
    return LodgifyApiRatesModelsV2CalendarPriceToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarPriceToJSONTyped(value?: LodgifyApiRatesModelsV2CalendarPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_stay': value['minStay'],
        'max_stay': value['maxStay'],
        'price_per_day': value['pricePerDay'],
        'price_per_additional_guest': value['pricePerAdditionalGuest'],
        'additional_guests_starts_from': value['additionalGuestsStartsFrom'],
    };
}

