/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object used to checkin a booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto {
    /**
     * Time of the checkin (in the property's timezone). Use format HH:mm:ss
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto
     */
    time: string;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto {
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
    };
}

