/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2MessagingThreadGuidGet200ResponseInnerMessagesInner } from './V2MessagingThreadGuidGet200ResponseInnerMessagesInner';
import {
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerFromJSON,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerFromJSONTyped,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerToJSON,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerToJSONTyped,
} from './V2MessagingThreadGuidGet200ResponseInnerMessagesInner';

/**
 * Object to hold the details of a thread
 * @export
 * @interface LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
 */
export interface LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto {
    /**
     * The thread's unique identifier
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    threadUid?: string;
    /**
     * The thread's guest name
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    guestName?: string | null;
    /**
     * The thread's guest email
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    guestEmail?: string | null;
    /**
     * Date and time of the last message in the thread
     * @type {Date}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    lastMessageDate?: Date;
    /**
     * Read status of the thread
     * @type {boolean}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    isRead?: boolean;
    /**
     * List of messages in the thread
     * @type {Array<V2MessagingThreadGuidGet200ResponseInnerMessagesInner>}
     * @memberof LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto
     */
    messages?: Array<V2MessagingThreadGuidGet200ResponseInnerMessagesInner> | null;
}

/**
 * Check if a given object implements the LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto interface.
 */
export function instanceOfLodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto(value: object): value is LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto {
    return true;
}

export function LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoFromJSON(json: any): LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto {
    return LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoFromJSONTyped(json, false);
}

export function LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'threadUid': json['thread_uid'] == null ? undefined : json['thread_uid'],
        'guestName': json['guest_name'] == null ? undefined : json['guest_name'],
        'guestEmail': json['guest_email'] == null ? undefined : json['guest_email'],
        'lastMessageDate': json['last_message_date'] == null ? undefined : (new Date(json['last_message_date'])),
        'isRead': json['is_read'] == null ? undefined : json['is_read'],
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(V2MessagingThreadGuidGet200ResponseInnerMessagesInnerFromJSON)),
    };
}

export function LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoToJSON(json: any): LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto {
    return LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoToJSONTyped(json, false);
}

export function LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDtoToJSONTyped(value?: LodgifyMessagingLegacyPublicApiModelsThreadItemListDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thread_uid': value['threadUid'],
        'guest_name': value['guestName'],
        'guest_email': value['guestEmail'],
        'last_message_date': value['lastMessageDate'] == null ? undefined : ((value['lastMessageDate']).toISOString()),
        'is_read': value['isRead'],
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(V2MessagingThreadGuidGet200ResponseInnerMessagesInnerToJSON)),
    };
}

