/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiPropertiesModelsV2ContactInfoDto
 */
export interface LodgifyApiPropertiesModelsV2ContactInfoDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof LodgifyApiPropertiesModelsV2ContactInfoDto
     */
    spokenLanguages?: Array<string> | null;
}

/**
 * Check if a given object implements the LodgifyApiPropertiesModelsV2ContactInfoDto interface.
 */
export function instanceOfLodgifyApiPropertiesModelsV2ContactInfoDto(value: object): value is LodgifyApiPropertiesModelsV2ContactInfoDto {
    return true;
}

export function LodgifyApiPropertiesModelsV2ContactInfoDtoFromJSON(json: any): LodgifyApiPropertiesModelsV2ContactInfoDto {
    return LodgifyApiPropertiesModelsV2ContactInfoDtoFromJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2ContactInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPropertiesModelsV2ContactInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'spokenLanguages': json['spoken_languages'] == null ? undefined : json['spoken_languages'],
    };
}

export function LodgifyApiPropertiesModelsV2ContactInfoDtoToJSON(json: any): LodgifyApiPropertiesModelsV2ContactInfoDto {
    return LodgifyApiPropertiesModelsV2ContactInfoDtoToJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2ContactInfoDtoToJSONTyped(value?: LodgifyApiPropertiesModelsV2ContactInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spoken_languages': value['spokenLanguages'],
    };
}

