/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto {
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
     */
    dateDue?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
     */
    isCurrent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto
     */
    status?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'dateDue': json['date_due'] == null ? undefined : json['date_due'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'isCurrent': json['is_current'] == null ? undefined : json['is_current'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteQuoteScheduledTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'date_due': value['dateDue'],
        'amount': value['amount'],
        'is_current': value['isCurrent'],
        'status': value['status'],
    };
}

