/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseRateSettingsFeesInnerPrice } from './RatesCalendarV2200ResponseRateSettingsFeesInnerPrice';
import {
    RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSON,
    RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSON,
    RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsFeesInnerPrice';

/**
 * Rate fee
 * @export
 * @interface LodgifyApiRatesModelsV2RateFee
 */
export interface LodgifyApiRatesModelsV2RateFee {
    /**
     * Name of the fee
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    feeName?: string | null;
    /**
     * Type of the fee
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    feeType?: string | null;
    /**
     * Fee is applied only if the stay of nights is less or equal than the amount nights
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    appliedForNights?: number | null;
    /**
     * Type of charge. Possible values are: "PerQuantity", "SingleCharge", "PerPerson", or "PerRoom"
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    chargeType?: string | null;
    /**
     * Frequency, can be either "PerStay" or "PerNight"
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    frequency?: string | null;
    /**
     * 
     * @type {RatesCalendarV2200ResponseRateSettingsFeesInnerPrice}
     * @memberof LodgifyApiRatesModelsV2RateFee
     */
    price?: RatesCalendarV2200ResponseRateSettingsFeesInnerPrice;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2RateFee interface.
 */
export function instanceOfLodgifyApiRatesModelsV2RateFee(value: object): value is LodgifyApiRatesModelsV2RateFee {
    return true;
}

export function LodgifyApiRatesModelsV2RateFeeFromJSON(json: any): LodgifyApiRatesModelsV2RateFee {
    return LodgifyApiRatesModelsV2RateFeeFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RateFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2RateFee {
    if (json == null) {
        return json;
    }
    return {
        
        'feeName': json['fee_name'] == null ? undefined : json['fee_name'],
        'feeType': json['fee_type'] == null ? undefined : json['fee_type'],
        'appliedForNights': json['applied_for_nights'] == null ? undefined : json['applied_for_nights'],
        'chargeType': json['charge_type'] == null ? undefined : json['charge_type'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'price': json['price'] == null ? undefined : RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSON(json['price']),
    };
}

export function LodgifyApiRatesModelsV2RateFeeToJSON(json: any): LodgifyApiRatesModelsV2RateFee {
    return LodgifyApiRatesModelsV2RateFeeToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RateFeeToJSONTyped(value?: LodgifyApiRatesModelsV2RateFee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee_name': value['feeName'],
        'fee_type': value['feeType'],
        'applied_for_nights': value['appliedForNights'],
        'charge_type': value['chargeType'],
        'frequency': value['frequency'],
        'price': RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSON(value['price']),
    };
}

