/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of transaction
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum = {
    Payment: 'Payment',
    Refund: 'Refund',
    Show: 'Show',
    Authorization: 'Authorization',
    Void: 'Void',
    Capture: 'Capture'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionTypeEnum;
}

