/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice } from './RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice';
import {
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice';

/**
 * Rate tax
 * @export
 * @interface LodgifyApiRatesModelsV2RateTax
 */
export interface LodgifyApiRatesModelsV2RateTax {
    /**
     * Name of the tax
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateTax
     */
    taxName?: string | null;
    /**
     * Type of the tax
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateTax
     */
    taxType?: string | null;
    /**
     * Type of charge. Possible values are: "PerQuantity", "SingleCharge", "PerPerson", or "PerRoom"
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateTax
     */
    chargeType?: string | null;
    /**
     * Frequency, can be either "PerStay" or "PerNight"
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RateTax
     */
    frequency?: string | null;
    /**
     * 
     * @type {RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice}
     * @memberof LodgifyApiRatesModelsV2RateTax
     */
    price?: RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2RateTax interface.
 */
export function instanceOfLodgifyApiRatesModelsV2RateTax(value: object): value is LodgifyApiRatesModelsV2RateTax {
    return true;
}

export function LodgifyApiRatesModelsV2RateTaxFromJSON(json: any): LodgifyApiRatesModelsV2RateTax {
    return LodgifyApiRatesModelsV2RateTaxFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RateTaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2RateTax {
    if (json == null) {
        return json;
    }
    return {
        
        'taxName': json['tax_name'] == null ? undefined : json['tax_name'],
        'taxType': json['tax_type'] == null ? undefined : json['tax_type'],
        'chargeType': json['charge_type'] == null ? undefined : json['charge_type'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'price': json['price'] == null ? undefined : RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSON(json['price']),
    };
}

export function LodgifyApiRatesModelsV2RateTaxToJSON(json: any): LodgifyApiRatesModelsV2RateTax {
    return LodgifyApiRatesModelsV2RateTaxToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RateTaxToJSONTyped(value?: LodgifyApiRatesModelsV2RateTax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tax_name': value['taxName'],
        'tax_type': value['taxType'],
        'charge_type': value['chargeType'],
        'frequency': value['frequency'],
        'price': RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSON(value['price']),
    };
}

