/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyRatesModelsV1BookingSettingsBookingType = {
    InstantBooking: 'InstantBooking',
    BookingRequest: 'BookingRequest',
    EnquiryOnly: 'EnquiryOnly'
} as const;
export type LodgifyRatesModelsV1BookingSettingsBookingType = typeof LodgifyRatesModelsV1BookingSettingsBookingType[keyof typeof LodgifyRatesModelsV1BookingSettingsBookingType];


export function instanceOfLodgifyRatesModelsV1BookingSettingsBookingType(value: any): boolean {
    for (const key in LodgifyRatesModelsV1BookingSettingsBookingType) {
        if (Object.prototype.hasOwnProperty.call(LodgifyRatesModelsV1BookingSettingsBookingType, key)) {
            if (LodgifyRatesModelsV1BookingSettingsBookingType[key as keyof typeof LodgifyRatesModelsV1BookingSettingsBookingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyRatesModelsV1BookingSettingsBookingTypeFromJSON(json: any): LodgifyRatesModelsV1BookingSettingsBookingType {
    return LodgifyRatesModelsV1BookingSettingsBookingTypeFromJSONTyped(json, false);
}

export function LodgifyRatesModelsV1BookingSettingsBookingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyRatesModelsV1BookingSettingsBookingType {
    return json as LodgifyRatesModelsV1BookingSettingsBookingType;
}

export function LodgifyRatesModelsV1BookingSettingsBookingTypeToJSON(value?: LodgifyRatesModelsV1BookingSettingsBookingType | null): any {
    return value as any;
}

export function LodgifyRatesModelsV1BookingSettingsBookingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyRatesModelsV1BookingSettingsBookingType {
    return value as LodgifyRatesModelsV1BookingSettingsBookingType;
}

