/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2QuotePropertyIdGet200ResponseInnerOtherItemsInner } from './V2QuotePropertyIdGet200ResponseInnerOtherItemsInner';
import {
    V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerOtherItemsInner';
import type { V2QuotePropertyIdGet200ResponseInnerRoomTypesInner } from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInner';
import {
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInner';
import type { V2QuotePropertyIdGet200ResponseInnerAddOnsInner } from './V2QuotePropertyIdGet200ResponseInnerAddOnsInner';
import {
    V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerAddOnsInner';
import type { V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner } from './V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner';
import {
    V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner';

/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteQuoteDto {
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    totalIncludingVat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    totalExcludingVat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    totalVat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    propertyId?: number;
    /**
     * 
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    dateArrival?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    dateDeparture?: Date;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    currencyCode?: string | null;
    /**
     * Room types belonging to the Quote
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    roomTypes?: Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInner> | null;
    /**
     * Add-ons belonging to the Quote
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerAddOnsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    addOns?: Array<V2QuotePropertyIdGet200ResponseInnerAddOnsInner> | null;
    /**
     * Other items belonging to the Quote
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerOtherItemsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    otherItems?: Array<V2QuotePropertyIdGet200ResponseInnerOtherItemsInner> | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    addOnsSubtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    ratePolicyUserId?: number | null;
    /**
     * 
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    scheduledPayments?: Array<V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner> | null;
    /**
     * 
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    scheduledDamageProtection?: Array<V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner> | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    securityDeposit?: number;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    totalScheduledPayments?: number;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    totalToCollectManually?: number;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    amountGross?: number;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    rentalAgreement?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    cancellationPolicyText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    securityDepositText?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteDto
     */
    isVerification?: boolean;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteQuoteDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuoteDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteQuoteDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuoteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalIncludingVat': json['total_including_vat'] == null ? undefined : json['total_including_vat'],
        'totalExcludingVat': json['total_excluding_vat'] == null ? undefined : json['total_excluding_vat'],
        'totalVat': json['total_vat'] == null ? undefined : json['total_vat'],
        'propertyId': json['property_id'] == null ? undefined : json['property_id'],
        'dateArrival': json['date_arrival'] == null ? undefined : (new Date(json['date_arrival'])),
        'dateDeparture': json['date_departure'] == null ? undefined : (new Date(json['date_departure'])),
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'roomTypes': json['room_types'] == null ? undefined : ((json['room_types'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerFromJSON)),
        'addOns': json['add_ons'] == null ? undefined : ((json['add_ons'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSON)),
        'otherItems': json['other_items'] == null ? undefined : ((json['other_items'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSON)),
        'addOnsSubtotal': json['add_ons_subtotal'] == null ? undefined : json['add_ons_subtotal'],
        'ratePolicyUserId': json['rate_policy_user_id'] == null ? undefined : json['rate_policy_user_id'],
        'scheduledPayments': json['scheduled_payments'] == null ? undefined : ((json['scheduled_payments'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSON)),
        'scheduledDamageProtection': json['scheduled_damage_protection'] == null ? undefined : ((json['scheduled_damage_protection'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSON)),
        'securityDeposit': json['security_deposit'] == null ? undefined : json['security_deposit'],
        'totalScheduledPayments': json['total_scheduled_payments'] == null ? undefined : json['total_scheduled_payments'],
        'totalToCollectManually': json['total_to_collect_manually'] == null ? undefined : json['total_to_collect_manually'],
        'amountGross': json['amount_gross'] == null ? undefined : json['amount_gross'],
        'rentalAgreement': json['rental_agreement'] == null ? undefined : json['rental_agreement'],
        'cancellationPolicyText': json['cancellation_policy_text'] == null ? undefined : json['cancellation_policy_text'],
        'securityDepositText': json['security_deposit_text'] == null ? undefined : json['security_deposit_text'],
        'isVerification': json['is_verification'] == null ? undefined : json['is_verification'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteQuoteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_including_vat': value['totalIncludingVat'],
        'total_excluding_vat': value['totalExcludingVat'],
        'total_vat': value['totalVat'],
        'property_id': value['propertyId'],
        'date_arrival': value['dateArrival'] == null ? undefined : ((value['dateArrival']).toISOString()),
        'date_departure': value['dateDeparture'] == null ? undefined : ((value['dateDeparture']).toISOString()),
        'currency_code': value['currencyCode'],
        'room_types': value['roomTypes'] == null ? undefined : ((value['roomTypes'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerToJSON)),
        'add_ons': value['addOns'] == null ? undefined : ((value['addOns'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSON)),
        'other_items': value['otherItems'] == null ? undefined : ((value['otherItems'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSON)),
        'add_ons_subtotal': value['addOnsSubtotal'],
        'rate_policy_user_id': value['ratePolicyUserId'],
        'scheduled_payments': value['scheduledPayments'] == null ? undefined : ((value['scheduledPayments'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSON)),
        'scheduled_damage_protection': value['scheduledDamageProtection'] == null ? undefined : ((value['scheduledDamageProtection'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSON)),
        'security_deposit': value['securityDeposit'],
        'total_scheduled_payments': value['totalScheduledPayments'],
        'total_to_collect_manually': value['totalToCollectManually'],
        'amount_gross': value['amountGross'],
        'rental_agreement': value['rentalAgreement'],
        'cancellation_policy_text': value['cancellationPolicyText'],
        'security_deposit_text': value['securityDepositText'],
        'is_verification': value['isVerification'],
    };
}

