/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Guest information related to the Booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto {
    /**
     * Name of the guest
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto
     */
    name?: string | null;
    /**
     * Email of the guest
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto
     */
    email?: string | null;
    /**
     * Phone number of the guest
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto
     */
    phone?: string | null;
    /**
     * Code of the country the Guest is from
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto
     */
    countryCode?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsGuestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'country_code': value['countryCode'],
    };
}

