/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInner } from './V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInner';
import {
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerFromJSON,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerFromJSONTyped,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerToJSON,
    V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerToJSONTyped,
} from './V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInner';

/**
 * Object to hold a message details within a thread
 * @export
 * @interface LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
 */
export interface LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto {
    /**
     * Message Id
     * @type {number}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    id?: number;
    /**
     * Message subject
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    subject?: string | null;
    /**
     * Message body (You can expect HTML content)
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    message?: string | null;
    /**
     * Message type: Owner, Renter
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    type?: string | null;
    /**
     * Creation date of the message
     * @type {Date}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    dateCreated?: Date;
    /**
     * List of attachments in the message
     * @type {Array<V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInner>}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    attachments?: Array<V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInner> | null;
    /**
     * Message status: Submitted, Sent, Delivered, Failed
     * @type {string}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    messageStatus?: string | null;
    /**
     * Read status of the message
     * @type {boolean}
     * @memberof LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto
     */
    isRead?: boolean;
}

/**
 * Check if a given object implements the LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto interface.
 */
export function instanceOfLodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto(value: object): value is LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto {
    return true;
}

export function LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoFromJSON(json: any): LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto {
    return LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoFromJSONTyped(json, false);
}

export function LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'dateCreated': json['date_created'] == null ? undefined : (new Date(json['date_created'])),
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerFromJSON)),
        'messageStatus': json['message_status'] == null ? undefined : json['message_status'],
        'isRead': json['is_read'] == null ? undefined : json['is_read'],
    };
}

export function LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoToJSON(json: any): LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto {
    return LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoToJSONTyped(json, false);
}

export function LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDtoToJSONTyped(value?: LodgifyMessagingLegacyPublicApiModelsInboxDetailMessageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'subject': value['subject'],
        'message': value['message'],
        'type': value['type'],
        'date_created': value['dateCreated'] == null ? undefined : ((value['dateCreated']).toISOString()),
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(V2MessagingThreadGuidGet200ResponseInnerMessagesInnerAttachmentsInnerToJSON)),
        'message_status': value['messageStatus'],
        'is_read': value['isRead'],
    };
}

