/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInner } from './RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInner';
import {
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerFromJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerToJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInner';
import type { RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice } from './RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice';
import {
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice';
import type { RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner } from './RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner';
import {
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerFromJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerToJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner';

/**
 * Rate promotion
 * @export
 * @interface LodgifyApiRatesModelsV2RatePromotion
 */
export interface LodgifyApiRatesModelsV2RatePromotion {
    /**
     * Promotion name
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    name?: string | null;
    /**
     * 
     * @type {RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    price?: RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice;
    /**
     * Indicates the amount of nights or more before arrival to apply the promotion
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    earlyBookerDays?: number | null;
    /**
     * Indicates the amount of days nights or less before arrival to apply the promotion
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    lastMinuteDays?: number | null;
    /**
     * Indicates the type nights minimum stay required to apply the promotion
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    minimumStayDays?: number | null;
    /**
     * Promotion is applied only if booked during the specific date range
     * @type {Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner>}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    bookingDates?: Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner> | null;
    /**
     * Date range when the promotion applies
     * @type {Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner>}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    stayDates?: Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInner> | null;
    /**
     * List of valid codes applied to this promotion
     * @type {Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInner>}
     * @memberof LodgifyApiRatesModelsV2RatePromotion
     */
    codes?: Array<RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2RatePromotion interface.
 */
export function instanceOfLodgifyApiRatesModelsV2RatePromotion(value: object): value is LodgifyApiRatesModelsV2RatePromotion {
    return true;
}

export function LodgifyApiRatesModelsV2RatePromotionFromJSON(json: any): LodgifyApiRatesModelsV2RatePromotion {
    return LodgifyApiRatesModelsV2RatePromotionFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2RatePromotion {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSON(json['price']),
        'earlyBookerDays': json['early_booker_days'] == null ? undefined : json['early_booker_days'],
        'lastMinuteDays': json['last_minute_days'] == null ? undefined : json['last_minute_days'],
        'minimumStayDays': json['minimum_stay_days'] == null ? undefined : json['minimum_stay_days'],
        'bookingDates': json['booking_dates'] == null ? undefined : ((json['booking_dates'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerFromJSON)),
        'stayDates': json['stay_dates'] == null ? undefined : ((json['stay_dates'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerFromJSON)),
        'codes': json['codes'] == null ? undefined : ((json['codes'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerFromJSON)),
    };
}

export function LodgifyApiRatesModelsV2RatePromotionToJSON(json: any): LodgifyApiRatesModelsV2RatePromotion {
    return LodgifyApiRatesModelsV2RatePromotionToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePromotionToJSONTyped(value?: LodgifyApiRatesModelsV2RatePromotion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSON(value['price']),
        'early_booker_days': value['earlyBookerDays'],
        'last_minute_days': value['lastMinuteDays'],
        'minimum_stay_days': value['minimumStayDays'],
        'booking_dates': value['bookingDates'] == null ? undefined : ((value['bookingDates'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerToJSON)),
        'stay_dates': value['stayDates'] == null ? undefined : ((value['stayDates'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerBookingDatesInnerToJSON)),
        'codes': value['codes'] == null ? undefined : ((value['codes'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerCodesInnerToJSON)),
    };
}

