/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rate promotion code
 * @export
 * @interface LodgifyApiRatesModelsV2RatePromotionCode
 */
export interface LodgifyApiRatesModelsV2RatePromotionCode {
    /**
     * Promotion code
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RatePromotionCode
     */
    code?: string | null;
    /**
     * Indicates if the promotion code is active
     * @type {boolean}
     * @memberof LodgifyApiRatesModelsV2RatePromotionCode
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2RatePromotionCode interface.
 */
export function instanceOfLodgifyApiRatesModelsV2RatePromotionCode(value: object): value is LodgifyApiRatesModelsV2RatePromotionCode {
    return true;
}

export function LodgifyApiRatesModelsV2RatePromotionCodeFromJSON(json: any): LodgifyApiRatesModelsV2RatePromotionCode {
    return LodgifyApiRatesModelsV2RatePromotionCodeFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePromotionCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2RatePromotionCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function LodgifyApiRatesModelsV2RatePromotionCodeToJSON(json: any): LodgifyApiRatesModelsV2RatePromotionCode {
    return LodgifyApiRatesModelsV2RatePromotionCodeToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePromotionCodeToJSONTyped(value?: LodgifyApiRatesModelsV2RatePromotionCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'is_active': value['isActive'],
    };
}

