/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of source the Booking comes from
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum = {
    Manual: 'Manual',
    Oh: 'OH',
    NineFlats: 'NineFlats',
    Airbnb: 'Airbnb',
    AirbnbIntegration: 'AirbnbIntegration',
    HomeAway: 'HomeAway',
    BookingCom: 'BookingCom',
    Expedia: 'Expedia',
    ICal: 'ICal',
    Email: 'Email',
    FacebookMessenger: 'FacebookMessenger',
    PublicApi: 'PublicApi',
    Other: 'Other'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingsSourceEnum;
}

