/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown } from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';
import {
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSONTyped,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';

/**
 * Room type parameters
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto {
    /**
     * RoomType identifier
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto
     */
    id?: number;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto
     */
    guestBreakdown: GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown;
    /**
     * Deprecated. Map to GuestBreakdown.Adults
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto
     * @deprecated
     */
    people?: number;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto {
    if (!('guestBreakdown' in value) || value['guestBreakdown'] === undefined) return false;
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto {
    return LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'guestBreakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON(json['guest_breakdown']),
        'people': json['people'] == null ? undefined : json['people'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto {
    return LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteRoomTypeParamDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'guest_breakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON(value['guestBreakdown']),
        'people': value['people'],
    };
}

