/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a payment link for a booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV12PaymentLinkDto
 */
export interface LodgifyApiPublicReservationsModelsV12PaymentLinkDto {
    /**
     * Url address to the payment page
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV12PaymentLinkDto
     */
    url?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV12PaymentLinkDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV12PaymentLinkDto(value: object): value is LodgifyApiPublicReservationsModelsV12PaymentLinkDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV12PaymentLinkDto {
    return LodgifyApiPublicReservationsModelsV12PaymentLinkDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV12PaymentLinkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV12PaymentLinkDto {
    return LodgifyApiPublicReservationsModelsV12PaymentLinkDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV12PaymentLinkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

