/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum = {
    False: 'False',
    True: 'True',
    All: 'All'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingsTrashEnum;
}

