/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto
 */
export interface LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto {
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto
     */
    id?: number;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto(value: object): value is LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2AvailabilityClosedPeriodAvailabilityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

