/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rate fee price
 * @export
 * @interface RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
 */
export interface RatesCalendarV2200ResponseRateSettingsFeesInnerPrice {
    /**
     * Indicates if the fee price is vat exclusive
     * @type {boolean}
     * @memberof RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
     */
    isVatExclusive?: boolean;
    /**
     * VAT percentage value (only defined if not inclusive)
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
     */
    vatPercentage?: number;
    /**
     * Rate type, equals "Fixed" for a fixed amount price, "Percentage" for a percentage price
     * @type {string}
     * @memberof RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
     */
    rateType?: string | null;
    /**
     * 
     * @type {object}
     * @memberof RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
     */
    amount?: object;
    /**
     * Price value percentage
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettingsFeesInnerPrice
     */
    percentage?: number | null;
}

/**
 * Check if a given object implements the RatesCalendarV2200ResponseRateSettingsFeesInnerPrice interface.
 */
export function instanceOfRatesCalendarV2200ResponseRateSettingsFeesInnerPrice(value: object): value is RatesCalendarV2200ResponseRateSettingsFeesInnerPrice {
    return true;
}

export function RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSON(json: any): RatesCalendarV2200ResponseRateSettingsFeesInnerPrice {
    return RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsFeesInnerPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesCalendarV2200ResponseRateSettingsFeesInnerPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'isVatExclusive': json['is_vat_exclusive'] == null ? undefined : json['is_vat_exclusive'],
        'vatPercentage': json['vat_percentage'] == null ? undefined : json['vat_percentage'],
        'rateType': json['rate_type'] == null ? undefined : json['rate_type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSON(json: any): RatesCalendarV2200ResponseRateSettingsFeesInnerPrice {
    return RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsFeesInnerPriceToJSONTyped(value?: RatesCalendarV2200ResponseRateSettingsFeesInnerPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_vat_exclusive': value['isVatExclusive'],
        'vat_percentage': value['vatPercentage'],
        'rate_type': value['rateType'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

