/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateKeyCodesRequestRoomsInner } from './UpdateKeyCodesRequestRoomsInner';
import {
    UpdateKeyCodesRequestRoomsInnerFromJSON,
    UpdateKeyCodesRequestRoomsInnerFromJSONTyped,
    UpdateKeyCodesRequestRoomsInnerToJSON,
    UpdateKeyCodesRequestRoomsInnerToJSONTyped,
} from './UpdateKeyCodesRequestRoomsInner';

/**
 * Represents a Booking with the list of room types and keycodes to access to the properties rented.
 * @export
 * @interface UpdateKeyCodesRequest
 */
export interface UpdateKeyCodesRequest {
    /**
     * List of room types of the booking.
     * @type {Array<UpdateKeyCodesRequestRoomsInner>}
     * @memberof UpdateKeyCodesRequest
     */
    rooms?: Array<UpdateKeyCodesRequestRoomsInner> | null;
}

/**
 * Check if a given object implements the UpdateKeyCodesRequest interface.
 */
export function instanceOfUpdateKeyCodesRequest(value: object): value is UpdateKeyCodesRequest {
    return true;
}

export function UpdateKeyCodesRequestFromJSON(json: any): UpdateKeyCodesRequest {
    return UpdateKeyCodesRequestFromJSONTyped(json, false);
}

export function UpdateKeyCodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateKeyCodesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rooms': json['rooms'] == null ? undefined : ((json['rooms'] as Array<any>).map(UpdateKeyCodesRequestRoomsInnerFromJSON)),
    };
}

export function UpdateKeyCodesRequestToJSON(json: any): UpdateKeyCodesRequest {
    return UpdateKeyCodesRequestToJSONTyped(json, false);
}

export function UpdateKeyCodesRequestToJSONTyped(value?: UpdateKeyCodesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rooms': value['rooms'] == null ? undefined : ((value['rooms'] as Array<any>).map(UpdateKeyCodesRequestRoomsInnerToJSON)),
    };
}

