/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2QuotePropertyIdGet200ResponseInnerOtherItemsInner
 */
export interface V2QuotePropertyIdGet200ResponseInnerOtherItemsInner {
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerOtherItemsInner
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerOtherItemsInner
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerOtherItemsInner
     */
    amount?: number;
}

/**
 * Check if a given object implements the V2QuotePropertyIdGet200ResponseInnerOtherItemsInner interface.
 */
export function instanceOfV2QuotePropertyIdGet200ResponseInnerOtherItemsInner(value: object): value is V2QuotePropertyIdGet200ResponseInnerOtherItemsInner {
    return true;
}

export function V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSON(json: any): V2QuotePropertyIdGet200ResponseInnerOtherItemsInner {
    return V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2QuotePropertyIdGet200ResponseInnerOtherItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSON(json: any): V2QuotePropertyIdGet200ResponseInnerOtherItemsInner {
    return V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerOtherItemsInnerToJSONTyped(value?: V2QuotePropertyIdGet200ResponseInnerOtherItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'amount': value['amount'],
    };
}

