/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown } from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';
import {
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSONTyped,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';

/**
 * Room type parameters
 * @export
 * @interface V2QuotePropertyIdGetRoomTypesParameterInner
 */
export interface V2QuotePropertyIdGetRoomTypesParameterInner {
    /**
     * RoomType identifier
     * @type {number}
     * @memberof V2QuotePropertyIdGetRoomTypesParameterInner
     */
    id?: number;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown}
     * @memberof V2QuotePropertyIdGetRoomTypesParameterInner
     */
    guestBreakdown: GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown;
    /**
     * Deprecated. Map to GuestBreakdown.Adults
     * @type {number}
     * @memberof V2QuotePropertyIdGetRoomTypesParameterInner
     * @deprecated
     */
    people?: number;
}

/**
 * Check if a given object implements the V2QuotePropertyIdGetRoomTypesParameterInner interface.
 */
export function instanceOfV2QuotePropertyIdGetRoomTypesParameterInner(value: object): value is V2QuotePropertyIdGetRoomTypesParameterInner {
    if (!('guestBreakdown' in value) || value['guestBreakdown'] === undefined) return false;
    return true;
}

export function V2QuotePropertyIdGetRoomTypesParameterInnerFromJSON(json: any): V2QuotePropertyIdGetRoomTypesParameterInner {
    return V2QuotePropertyIdGetRoomTypesParameterInnerFromJSONTyped(json, false);
}

export function V2QuotePropertyIdGetRoomTypesParameterInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2QuotePropertyIdGetRoomTypesParameterInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'guestBreakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON(json['guest_breakdown']),
        'people': json['people'] == null ? undefined : json['people'],
    };
}

export function V2QuotePropertyIdGetRoomTypesParameterInnerToJSON(json: any): V2QuotePropertyIdGetRoomTypesParameterInner {
    return V2QuotePropertyIdGetRoomTypesParameterInnerToJSONTyped(json, false);
}

export function V2QuotePropertyIdGetRoomTypesParameterInnerToJSONTyped(value?: V2QuotePropertyIdGetRoomTypesParameterInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'guest_breakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON(value['guestBreakdown']),
        'people': value['people'],
    };
}

