/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
 */
export interface V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner {
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
     */
    dateDue?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
     */
    isCurrent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner
     */
    status?: string | null;
}

/**
 * Check if a given object implements the V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner interface.
 */
export function instanceOfV2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner(value: object): value is V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner {
    return true;
}

export function V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSON(json: any): V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner {
    return V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'dateDue': json['date_due'] == null ? undefined : json['date_due'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'isCurrent': json['is_current'] == null ? undefined : json['is_current'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSON(json: any): V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner {
    return V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInnerToJSONTyped(value?: V2QuotePropertyIdGet200ResponseInnerScheduledPaymentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'date_due': value['dateDue'],
        'amount': value['amount'],
        'is_current': value['isCurrent'],
        'status': value['status'],
    };
}

