/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
 */
export interface V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner {
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
     */
    feeType?: V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFeeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner
     */
    roomRateType?: V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerRoomRateTypeEnum;
}


/**
 * @export
 */
export const V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFeeTypeEnum = {
    Cleaning: 'Cleaning',
    Miscellaneous: 'Miscellaneous',
    DamageProtectionInsurance: 'DamageProtectionInsurance',
    ManagementFee: 'ManagementFee',
    ServiceFee: 'ServiceFee',
    Wood: 'Wood',
    DrinkingWater: 'DrinkingWater',
    WaterCraftMooring: 'WaterCraftMooring',
    WaterCraft: 'WaterCraft',
    Water: 'Water',
    Vehicle: 'Vehicle',
    FoodUtensils: 'FoodUtensils',
    UtensilsCleaning: 'UtensilsCleaning',
    Transportation: 'Transportation',
    Tour: 'Tour',
    Toiletries: 'Toiletries',
    Spa: 'Spa',
    Resort: 'Resort',
    Rent: 'Rent',
    Parking: 'Parking',
    Phone: 'Phone',
    OnSitePaymentMethod: 'OnSitePaymentMethod',
    Oil: 'Oil',
    LinensBed: 'LinensBed',
    LinensBath: 'LinensBath',
    Linens: 'Linens',
    Laundry: 'Laundry',
    Labor: 'Labor',
    Internet: 'Internet',
    TravelInsurance: 'TravelInsurance',
    HotTub: 'HotTub',
    HighChair: 'HighChair',
    Heating: 'Heating',
    Gas: 'Gas',
    Gardening: 'Gardening',
    Food: 'Food',
    Equipment: 'Equipment',
    Electricity: 'Electricity',
    Concierge: 'Concierge',
    PoolHeating: 'PoolHeating',
    Pool: 'Pool',
    Class: 'Class',
    BabyBed: 'BabyBed',
    PropertyAssociation: 'PropertyAssociation',
    AirConditioning: 'AirConditioning',
    AdditionalBed: 'AdditionalBed',
    PetFee: 'PetFee',
    ServiceCharge: 'ServiceCharge',
    GratuityFee: 'GratuityFee',
    DamageWaiver: 'DamageWaiver',
    Community: 'Community'
} as const;
export type V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFeeTypeEnum = typeof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFeeTypeEnum[keyof typeof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFeeTypeEnum];

/**
 * @export
 */
export const V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerRoomRateTypeEnum = {
    Stay: 'Stay',
    ShortStayPremium: 'ShortStayPremium'
} as const;
export type V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerRoomRateTypeEnum = typeof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerRoomRateTypeEnum[keyof typeof V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerRoomRateTypeEnum];


/**
 * Check if a given object implements the V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner interface.
 */
export function instanceOfV2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner(value: object): value is V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner {
    return true;
}

export function V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSON(json: any): V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner {
    return V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'feeType': json['fee_type'] == null ? undefined : json['fee_type'],
        'roomRateType': json['room_rate_type'] == null ? undefined : json['room_rate_type'],
    };
}

export function V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSON(json: any): V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner {
    return V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSONTyped(value?: V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'description': value['description'],
        'amount': value['amount'],
        'fee_type': value['feeType'],
        'room_rate_type': value['roomRateType'],
    };
}

