/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object used to checkout a booking
 * @export
 * @interface V2ReservationsBookingsIdCheckoutPutRequest
 */
export interface V2ReservationsBookingsIdCheckoutPutRequest {
    /**
     * Time of the checkout (in the property's timezone). Use format HH:mm:ss
     * @type {string}
     * @memberof V2ReservationsBookingsIdCheckoutPutRequest
     */
    time: string;
}

/**
 * Check if a given object implements the V2ReservationsBookingsIdCheckoutPutRequest interface.
 */
export function instanceOfV2ReservationsBookingsIdCheckoutPutRequest(value: object): value is V2ReservationsBookingsIdCheckoutPutRequest {
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function V2ReservationsBookingsIdCheckoutPutRequestFromJSON(json: any): V2ReservationsBookingsIdCheckoutPutRequest {
    return V2ReservationsBookingsIdCheckoutPutRequestFromJSONTyped(json, false);
}

export function V2ReservationsBookingsIdCheckoutPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2ReservationsBookingsIdCheckoutPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function V2ReservationsBookingsIdCheckoutPutRequestToJSON(json: any): V2ReservationsBookingsIdCheckoutPutRequest {
    return V2ReservationsBookingsIdCheckoutPutRequestToJSONTyped(json, false);
}

export function V2ReservationsBookingsIdCheckoutPutRequestToJSONTyped(value?: V2ReservationsBookingsIdCheckoutPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
    };
}

