/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result of a Payment Link create request.
 * @export
 * @interface CreatePaymentLinkAsync200Response
 */
export interface CreatePaymentLinkAsync200Response {
    /**
     * When true, the payment link has been created with the specified amount.
     * When false, the payment link could not be created because there is a scheduled payment which is pending or the requested amount could not be enforced.
     * @type {boolean}
     * @memberof CreatePaymentLinkAsync200Response
     */
    succeeded?: boolean;
}

/**
 * Check if a given object implements the CreatePaymentLinkAsync200Response interface.
 */
export function instanceOfCreatePaymentLinkAsync200Response(value: object): value is CreatePaymentLinkAsync200Response {
    return true;
}

export function CreatePaymentLinkAsync200ResponseFromJSON(json: any): CreatePaymentLinkAsync200Response {
    return CreatePaymentLinkAsync200ResponseFromJSONTyped(json, false);
}

export function CreatePaymentLinkAsync200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentLinkAsync200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
    };
}

export function CreatePaymentLinkAsync200ResponseToJSON(json: any): CreatePaymentLinkAsync200Response {
    return CreatePaymentLinkAsync200ResponseToJSONTyped(json, false);
}

export function CreatePaymentLinkAsync200ResponseToJSONTyped(value?: CreatePaymentLinkAsync200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'succeeded': value['succeeded'],
    };
}

