/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllPropertiesAsync400Response
 */
export interface GetAllPropertiesAsync400Response {
    /**
     * 
     * @type {string}
     * @memberof GetAllPropertiesAsync400Response
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAllPropertiesAsync400Response
     */
    code?: GetAllPropertiesAsync400ResponseCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAllPropertiesAsync400Response
     */
    correlationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAllPropertiesAsync400Response
     */
    eventId?: string | null;
}


/**
 * @export
 */
export const GetAllPropertiesAsync400ResponseCodeEnum = {
    Unknown: 'Unknown',
    NoRateDefined: 'NoRateDefined',
    MinStayRequired: 'MinStayRequired',
    BookingStatusUnknown: 'BookingStatusUnknown',
    BookingMessageTypeNotAllowed: 'BookingMessageTypeNotAllowed',
    BookingNoRooms: 'BookingNoRooms',
    BookingCannotChangeStatus: 'BookingCannotChangeStatus',
    EnquiryAlreadyUpgraded: 'EnquiryAlreadyUpgraded',
    BookingPaymentNotValid: 'BookingPaymentNotValid',
    ArrivalNotValid: 'ArrivalNotValid',
    DepartureNotValid: 'DepartureNotValid',
    PropertyNotAvailable: 'PropertyNotAvailable',
    CaptchaInvalid: 'CaptchaInvalid',
    StripeError: 'StripeError',
    ValidationError: 'ValidationError',
    PaymentError: 'PaymentError',
    ArgumentError: 'ArgumentError',
    NotFound: 'NotFound',
    NotImplemented: 'NotImplemented',
    NotAuthorized: 'NotAuthorized'
} as const;
export type GetAllPropertiesAsync400ResponseCodeEnum = typeof GetAllPropertiesAsync400ResponseCodeEnum[keyof typeof GetAllPropertiesAsync400ResponseCodeEnum];


/**
 * Check if a given object implements the GetAllPropertiesAsync400Response interface.
 */
export function instanceOfGetAllPropertiesAsync400Response(value: object): value is GetAllPropertiesAsync400Response {
    return true;
}

export function GetAllPropertiesAsync400ResponseFromJSON(json: any): GetAllPropertiesAsync400Response {
    return GetAllPropertiesAsync400ResponseFromJSONTyped(json, false);
}

export function GetAllPropertiesAsync400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPropertiesAsync400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'correlationId': json['correlation_id'] == null ? undefined : json['correlation_id'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
    };
}

export function GetAllPropertiesAsync400ResponseToJSON(json: any): GetAllPropertiesAsync400Response {
    return GetAllPropertiesAsync400ResponseToJSONTyped(json, false);
}

export function GetAllPropertiesAsync400ResponseToJSONTyped(value?: GetAllPropertiesAsync400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'correlation_id': value['correlationId'],
        'event_id': value['eventId'],
    };
}

