/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllPropertiesAsync200ResponseItemsInnerContact
 */
export interface GetAllPropertiesAsync200ResponseItemsInnerContact {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAllPropertiesAsync200ResponseItemsInnerContact
     */
    spokenLanguages?: Array<string> | null;
}

/**
 * Check if a given object implements the GetAllPropertiesAsync200ResponseItemsInnerContact interface.
 */
export function instanceOfGetAllPropertiesAsync200ResponseItemsInnerContact(value: object): value is GetAllPropertiesAsync200ResponseItemsInnerContact {
    return true;
}

export function GetAllPropertiesAsync200ResponseItemsInnerContactFromJSON(json: any): GetAllPropertiesAsync200ResponseItemsInnerContact {
    return GetAllPropertiesAsync200ResponseItemsInnerContactFromJSONTyped(json, false);
}

export function GetAllPropertiesAsync200ResponseItemsInnerContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPropertiesAsync200ResponseItemsInnerContact {
    if (json == null) {
        return json;
    }
    return {
        
        'spokenLanguages': json['spoken_languages'] == null ? undefined : json['spoken_languages'],
    };
}

export function GetAllPropertiesAsync200ResponseItemsInnerContactToJSON(json: any): GetAllPropertiesAsync200ResponseItemsInnerContact {
    return GetAllPropertiesAsync200ResponseItemsInnerContactToJSONTyped(json, false);
}

export function GetAllPropertiesAsync200ResponseItemsInnerContactToJSONTyped(value?: GetAllPropertiesAsync200ResponseItemsInnerContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spoken_languages': value['spokenLanguages'],
    };
}

