/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown } from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';
import {
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSONTyped,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON,
    GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSONTyped,
} from './GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown';

/**
 * Room information related to the Booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerRoomsInner
 */
export interface GetAllAsync200ResponseItemsInnerRoomsInner {
    /**
     * Id of the room type booked
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInner
     */
    roomTypeId?: number;
    /**
     * 
     * @type {GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInner
     */
    guestBreakdown: GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdown;
    /**
     * Deprecated. Map to GuestBreakdown.Adults
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInner
     * @deprecated
     */
    people?: number;
    /**
     * KeyCode to access the property or room rented
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerRoomsInner
     */
    keyCode?: string | null;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerRoomsInner interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerRoomsInner(value: object): value is GetAllAsync200ResponseItemsInnerRoomsInner {
    if (!('guestBreakdown' in value) || value['guestBreakdown'] === undefined) return false;
    return true;
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerFromJSON(json: any): GetAllAsync200ResponseItemsInnerRoomsInner {
    return GetAllAsync200ResponseItemsInnerRoomsInnerFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerRoomsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'roomTypeId': json['room_type_id'] == null ? undefined : json['room_type_id'],
        'guestBreakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownFromJSON(json['guest_breakdown']),
        'people': json['people'] == null ? undefined : json['people'],
        'keyCode': json['key_code'] == null ? undefined : json['key_code'],
    };
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerToJSON(json: any): GetAllAsync200ResponseItemsInnerRoomsInner {
    return GetAllAsync200ResponseItemsInnerRoomsInnerToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerRoomsInnerToJSONTyped(value?: GetAllAsync200ResponseItemsInnerRoomsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'room_type_id': value['roomTypeId'],
        'guest_breakdown': GetAllAsync200ResponseItemsInnerRoomsInnerGuestBreakdownToJSON(value['guestBreakdown']),
        'people': value['people'],
        'key_code': value['keyCode'],
    };
}

