/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner
 */
export interface GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner {
    /**
     * 
     * @type {Date}
     * @memberof GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner
     */
    _for?: string | null;
}

/**
 * Check if a given object implements the GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner interface.
 */
export function instanceOfGetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner(value: object): value is GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner {
    return true;
}

export function GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSON(json: any): GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner {
    return GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSONTyped(json, false);
}

export function GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        '_for': json['for'] == null ? undefined : json['for'],
    };
}

export function GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSON(json: any): GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner {
    return GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSONTyped(json, false);
}

export function GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSONTyped(value?: GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'for': value['_for'],
    };
}

