/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about each transaction of the Booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerTransactionsInner
 */
export interface GetAllAsync200ResponseItemsInnerTransactionsInner {
    /**
     * Id of the transaction
     * @type {number}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    id?: number;
    /**
     * Type of transaction
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    type?: GetAllAsync200ResponseItemsInnerTransactionsInnerTypeEnum;
    /**
     * Information about the status of the Transaction
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    status?: GetAllAsync200ResponseItemsInnerTransactionsInnerStatusEnum;
    /**
     * Information about the payment type of the Transaction
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    paymentType?: GetAllAsync200ResponseItemsInnerTransactionsInnerPaymentTypeEnum;
    /**
     * Description of the transaction
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    description?: string | null;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    amount?: object;
    /**
     * The time the transaction was processed at
     * @type {Date}
     * @memberof GetAllAsync200ResponseItemsInnerTransactionsInner
     */
    processedAt?: Date | null;
}


/**
 * @export
 */
export const GetAllAsync200ResponseItemsInnerTransactionsInnerTypeEnum = {
    Payment: 'Payment',
    Refund: 'Refund',
    Show: 'Show',
    Authorization: 'Authorization',
    Void: 'Void',
    Capture: 'Capture'
} as const;
export type GetAllAsync200ResponseItemsInnerTransactionsInnerTypeEnum = typeof GetAllAsync200ResponseItemsInnerTransactionsInnerTypeEnum[keyof typeof GetAllAsync200ResponseItemsInnerTransactionsInnerTypeEnum];

/**
 * @export
 */
export const GetAllAsync200ResponseItemsInnerTransactionsInnerStatusEnum = {
    Requested: 'Requested',
    Processing: 'Processing',
    Done: 'Done',
    Failed: 'Failed',
    Canceled: 'Canceled',
    Abandoned: 'Abandoned',
    Unknown: 'Unknown'
} as const;
export type GetAllAsync200ResponseItemsInnerTransactionsInnerStatusEnum = typeof GetAllAsync200ResponseItemsInnerTransactionsInnerStatusEnum[keyof typeof GetAllAsync200ResponseItemsInnerTransactionsInnerStatusEnum];

/**
 * @export
 */
export const GetAllAsync200ResponseItemsInnerTransactionsInnerPaymentTypeEnum = {
    None: 'None',
    PaypalWallet: 'PaypalWallet',
    BankAccount: 'BankAccount',
    StripeSpreedly: 'StripeSpreedly',
    Payyo: 'Payyo',
    AuthorizeNetSpreedly: 'AuthorizeNetSpreedly',
    BraintreeSpreedly: 'BraintreeSpreedly',
    PayPalProSpreedly: 'PayPalProSpreedly',
    PciProxy: 'PciProxy',
    SpreedlyTestSpreedly: 'SpreedlyTestSpreedly',
    StripeSca: 'StripeSca',
    LodgifyPaymentsStripe: 'LodgifyPaymentsStripe'
} as const;
export type GetAllAsync200ResponseItemsInnerTransactionsInnerPaymentTypeEnum = typeof GetAllAsync200ResponseItemsInnerTransactionsInnerPaymentTypeEnum[keyof typeof GetAllAsync200ResponseItemsInnerTransactionsInnerPaymentTypeEnum];


/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerTransactionsInner interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerTransactionsInner(value: object): value is GetAllAsync200ResponseItemsInnerTransactionsInner {
    return true;
}

export function GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSON(json: any): GetAllAsync200ResponseItemsInnerTransactionsInner {
    return GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerTransactionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerTransactionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentType': json['payment_type'] == null ? undefined : json['payment_type'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'processedAt': json['processed_at'] == null ? undefined : (new Date(json['processed_at'])),
    };
}

export function GetAllAsync200ResponseItemsInnerTransactionsInnerToJSON(json: any): GetAllAsync200ResponseItemsInnerTransactionsInner {
    return GetAllAsync200ResponseItemsInnerTransactionsInnerToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerTransactionsInnerToJSONTyped(value?: GetAllAsync200ResponseItemsInnerTransactionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'payment_type': value['paymentType'],
        'description': value['description'],
        'amount': value['amount'],
        'processed_at': value['processedAt'] == null ? undefined : ((value['processedAt'] as any).toISOString()),
    };
}

