/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Guest information related to the Booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerGuest
 */
export interface GetAllAsync200ResponseItemsInnerGuest {
    /**
     * Name of the guest
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerGuest
     */
    name?: string | null;
    /**
     * Email of the guest
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerGuest
     */
    email?: string | null;
    /**
     * Phone number of the guest
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerGuest
     */
    phone?: string | null;
    /**
     * Code of the country the Guest is from
     * @type {string}
     * @memberof GetAllAsync200ResponseItemsInnerGuest
     */
    countryCode?: string | null;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerGuest interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerGuest(value: object): value is GetAllAsync200ResponseItemsInnerGuest {
    return true;
}

export function GetAllAsync200ResponseItemsInnerGuestFromJSON(json: any): GetAllAsync200ResponseItemsInnerGuest {
    return GetAllAsync200ResponseItemsInnerGuestFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerGuestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerGuest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
    };
}

export function GetAllAsync200ResponseItemsInnerGuestToJSON(json: any): GetAllAsync200ResponseItemsInnerGuest {
    return GetAllAsync200ResponseItemsInnerGuestToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerGuestToJSONTyped(value?: GetAllAsync200ResponseItemsInnerGuest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'country_code': value['countryCode'],
    };
}

