/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Subtotal information of the Booking
 * @export
 * @interface GetAllAsync200ResponseItemsInnerSubtotals
 */
export interface GetAllAsync200ResponseItemsInnerSubtotals {
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    stay?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    promotions?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    fees?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    taxes?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    addons?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAllAsync200ResponseItemsInnerSubtotals
     */
    vat?: object;
}

/**
 * Check if a given object implements the GetAllAsync200ResponseItemsInnerSubtotals interface.
 */
export function instanceOfGetAllAsync200ResponseItemsInnerSubtotals(value: object): value is GetAllAsync200ResponseItemsInnerSubtotals {
    return true;
}

export function GetAllAsync200ResponseItemsInnerSubtotalsFromJSON(json: any): GetAllAsync200ResponseItemsInnerSubtotals {
    return GetAllAsync200ResponseItemsInnerSubtotalsFromJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerSubtotalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllAsync200ResponseItemsInnerSubtotals {
    if (json == null) {
        return json;
    }
    return {
        
        'stay': json['stay'] == null ? undefined : json['stay'],
        'promotions': json['promotions'] == null ? undefined : json['promotions'],
        'fees': json['fees'] == null ? undefined : json['fees'],
        'taxes': json['taxes'] == null ? undefined : json['taxes'],
        'addons': json['addons'] == null ? undefined : json['addons'],
        'vat': json['vat'] == null ? undefined : json['vat'],
    };
}

export function GetAllAsync200ResponseItemsInnerSubtotalsToJSON(json: any): GetAllAsync200ResponseItemsInnerSubtotals {
    return GetAllAsync200ResponseItemsInnerSubtotalsToJSONTyped(json, false);
}

export function GetAllAsync200ResponseItemsInnerSubtotalsToJSONTyped(value?: GetAllAsync200ResponseItemsInnerSubtotals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stay': value['stay'],
        'promotions': value['promotions'],
        'fees': value['fees'],
        'taxes': value['taxes'],
        'addons': value['addons'],
        'vat': value['vat'],
    };
}

