/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about each transaction of the Booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto {
    /**
     * Id of the transaction
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    id?: number;
    /**
     * Type of transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    type?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoTypeEnum;
    /**
     * Information about the status of the Transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    status?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoStatusEnum;
    /**
     * Information about the payment type of the Transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    paymentType?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoPaymentTypeEnum;
    /**
     * Description of the transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    description?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    amount?: object;
    /**
     * The time the transaction was processed at
     * @type {Date}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto
     */
    processedAt?: Date | null;
}


/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoTypeEnum = {
    Payment: 'Payment',
    Refund: 'Refund',
    Show: 'Show',
    Authorization: 'Authorization',
    Void: 'Void',
    Capture: 'Capture'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoTypeEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoTypeEnum];

/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoStatusEnum = {
    Requested: 'Requested',
    Processing: 'Processing',
    Done: 'Done',
    Failed: 'Failed',
    Canceled: 'Canceled',
    Abandoned: 'Abandoned',
    Unknown: 'Unknown'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoStatusEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoStatusEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoStatusEnum];

/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoPaymentTypeEnum = {
    None: 'None',
    PaypalWallet: 'PaypalWallet',
    BankAccount: 'BankAccount',
    StripeSpreedly: 'StripeSpreedly',
    Payyo: 'Payyo',
    AuthorizeNetSpreedly: 'AuthorizeNetSpreedly',
    BraintreeSpreedly: 'BraintreeSpreedly',
    PayPalProSpreedly: 'PayPalProSpreedly',
    PciProxy: 'PciProxy',
    SpreedlyTestSpreedly: 'SpreedlyTestSpreedly',
    StripeSca: 'StripeSca',
    LodgifyPaymentsStripe: 'LodgifyPaymentsStripe'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoPaymentTypeEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoPaymentTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoPaymentTypeEnum];


/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentType': json['payment_type'] == null ? undefined : json['payment_type'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'processedAt': json['processed_at'] == null ? undefined : (new Date(json['processed_at'])),
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'payment_type': value['paymentType'],
        'description': value['description'],
        'amount': value['amount'],
        'processed_at': value['processedAt'] == null ? undefined : ((value['processedAt'] as any).toISOString()),
    };
}

