/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result of a Payment Link create request.
 * @export
 * @interface LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto
 */
export interface LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto {
    /**
     * When true, the payment link has been created with the specified amount.
     * When false, the payment link could not be created because there is a scheduled payment which is pending or the requested amount could not be enforced.
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto
     */
    succeeded?: boolean;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto(value: object): value is LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto {
    return LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
    };
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto {
    return LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV12PaymentLinkCreatedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'succeeded': value['succeeded'],
    };
}

