/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType = {
    RoomRate: 'RoomRate',
    Promotion: 'Promotion',
    Fee: 'Fee',
    AddOn: 'AddOn',
    Tax: 'Tax',
    Other: 'Other'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType = typeof LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType];


export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuoteItemType(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType, key)) {
            if (LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType[key as keyof typeof LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteItemTypeFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteItemTypeFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType {
    return json as LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteItemTypeToJSON(value?: LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteItemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType {
    return value as LodgifyApiPublicReservationsModelsV2QuoteQuoteItemType;
}

