/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner } from './GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner';
import {
    GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSON,
    GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSONTyped,
    GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSON,
    GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSONTyped,
} from './GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner';

/**
 * 
 * @export
 * @interface LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto
 */
export interface LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto {
    /**
     * 
     * @type {boolean}
     * @memberof LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto
     */
    isRestricted?: boolean;
    /**
     * 
     * @type {Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner>}
     * @memberof LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto
     */
    checkIn?: Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner> | null;
    /**
     * 
     * @type {Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner>}
     * @memberof LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto
     */
    checkOut?: Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner> | null;
    /**
     * 
     * @type {Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner>}
     * @memberof LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto
     */
    notAvailable?: Array<GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto interface.
 */
export function instanceOfLodgifyApiPropertiesModelsV2SearchResultSearchInOutDto(value: object): value is LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto {
    return true;
}

export function LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoFromJSON(json: any): LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto {
    return LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoFromJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isRestricted': json['is_restricted'] == null ? undefined : json['is_restricted'],
        'checkIn': json['check_in'] == null ? undefined : ((json['check_in'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSON)),
        'checkOut': json['check_out'] == null ? undefined : ((json['check_out'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSON)),
        'notAvailable': json['not_available'] == null ? undefined : ((json['not_available'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerFromJSON)),
    };
}

export function LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoToJSON(json: any): LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto {
    return LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoToJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2SearchResultSearchInOutDtoToJSONTyped(value?: LodgifyApiPropertiesModelsV2SearchResultSearchInOutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_restricted': value['isRestricted'],
        'check_in': value['checkIn'] == null ? undefined : ((value['checkIn'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSON)),
        'check_out': value['checkOut'] == null ? undefined : ((value['checkOut'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSON)),
        'not_available': value['notAvailable'] == null ? undefined : ((value['notAvailable'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerInOutCheckInInnerToJSON)),
    };
}

