/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInner } from './GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInner';
import {
    GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerFromJSON,
    GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerFromJSONTyped,
    GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerToJSON,
    GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerToJSONTyped,
} from './GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInner';
import type { GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod } from './GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod';
import {
    GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSON,
    GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSONTyped,
    GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSON,
    GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSONTyped,
} from './GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod';

/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
 */
export interface LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto {
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    start?: string;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    end?: string;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    available?: number;
    /**
     * 
     * @type {GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    closedPeriod?: GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod;
    /**
     * 
     * @type {Array<GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    bookings?: Array<GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInner> | null;
    /**
     * 
     * @type {Array<GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod>}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto
     */
    channelCalendars?: Array<GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriod> | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto(value: object): value is LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'available': json['available'] == null ? undefined : json['available'],
        'closedPeriod': json['closed_period'] == null ? undefined : GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSON(json['closed_period']),
        'bookings': json['bookings'] == null ? undefined : ((json['bookings'] as Array<any>).map(GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerFromJSON)),
        'channelCalendars': json['channel_calendars'] == null ? undefined : ((json['channel_calendars'] as Array<any>).map(GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodFromJSON)),
    };
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2AvailabilityPeriodDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'available': value['available'],
        'closed_period': GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSON(value['closedPeriod']),
        'bookings': value['bookings'] == null ? undefined : ((value['bookings'] as Array<any>).map(GetCalendarByUser200ResponseInnerPeriodsInnerBookingsInnerToJSON)),
        'channel_calendars': value['channelCalendars'] == null ? undefined : ((value['channelCalendars'] as Array<any>).map(GetCalendarByUser200ResponseInnerPeriodsInnerClosedPeriodToJSON)),
    };
}

