/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status information of the Booking
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum = {
    Open: 'Open',
    Tentative: 'Tentative',
    Booked: 'Booked',
    Declined: 'Declined'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingsStatusEnum;
}

