/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyRatesModelsV1DateRangeModel
 */
export interface LodgifyRatesModelsV1DateRangeModel {
    /**
     * 
     * @type {string}
     * @memberof LodgifyRatesModelsV1DateRangeModel
     */
    lower?: string;
    /**
     * 
     * @type {string}
     * @memberof LodgifyRatesModelsV1DateRangeModel
     */
    upper?: string;
}

/**
 * Check if a given object implements the LodgifyRatesModelsV1DateRangeModel interface.
 */
export function instanceOfLodgifyRatesModelsV1DateRangeModel(value: object): value is LodgifyRatesModelsV1DateRangeModel {
    return true;
}

export function LodgifyRatesModelsV1DateRangeModelFromJSON(json: any): LodgifyRatesModelsV1DateRangeModel {
    return LodgifyRatesModelsV1DateRangeModelFromJSONTyped(json, false);
}

export function LodgifyRatesModelsV1DateRangeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyRatesModelsV1DateRangeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'lower': json['lower'] == null ? undefined : json['lower'],
        'upper': json['upper'] == null ? undefined : json['upper'],
    };
}

export function LodgifyRatesModelsV1DateRangeModelToJSON(json: any): LodgifyRatesModelsV1DateRangeModel {
    return LodgifyRatesModelsV1DateRangeModelToJSONTyped(json, false);
}

export function LodgifyRatesModelsV1DateRangeModelToJSONTyped(value?: LodgifyRatesModelsV1DateRangeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lower': value['lower'],
        'upper': value['upper'],
    };
}

