/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents check-out for a booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel {
    /**
     * The check-out time
     * Format: HH:mm:ss
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel
     */
    time?: string | null;
    /**
     * The check-out source of change
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel
     */
    initiator?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'initiator': json['initiator'] == null ? undefined : json['initiator'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModelToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsCheckOutViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'initiator': value['initiator'],
    };
}

