/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about the payment type of the Transaction
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum = {
    None: 'None',
    PaypalWallet: 'PaypalWallet',
    BankAccount: 'BankAccount',
    StripeSpreedly: 'StripeSpreedly',
    Payyo: 'Payyo',
    AuthorizeNetSpreedly: 'AuthorizeNetSpreedly',
    BraintreeSpreedly: 'BraintreeSpreedly',
    PayPalProSpreedly: 'PayPalProSpreedly',
    PciProxy: 'PciProxy',
    SpreedlyTestSpreedly: 'SpreedlyTestSpreedly',
    StripeSca: 'StripeSca',
    LodgifyPaymentsStripe: 'LodgifyPaymentsStripe'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingTransactionsPaymentTypeEnum;
}

