/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rate price
 * @export
 * @interface LodgifyApiRatesModelsV2RatePrice
 */
export interface LodgifyApiRatesModelsV2RatePrice {
    /**
     * Rate type, equals "Fixed" for a fixed amount price, "Percentage" for a percentage price
     * @type {string}
     * @memberof LodgifyApiRatesModelsV2RatePrice
     */
    rateType?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiRatesModelsV2RatePrice
     */
    amount?: object;
    /**
     * Price value percentage
     * @type {number}
     * @memberof LodgifyApiRatesModelsV2RatePrice
     */
    percentage?: number | null;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2RatePrice interface.
 */
export function instanceOfLodgifyApiRatesModelsV2RatePrice(value: object): value is LodgifyApiRatesModelsV2RatePrice {
    return true;
}

export function LodgifyApiRatesModelsV2RatePriceFromJSON(json: any): LodgifyApiRatesModelsV2RatePrice {
    return LodgifyApiRatesModelsV2RatePriceFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2RatePrice {
    if (json == null) {
        return json;
    }
    return {
        
        'rateType': json['rate_type'] == null ? undefined : json['rate_type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function LodgifyApiRatesModelsV2RatePriceToJSON(json: any): LodgifyApiRatesModelsV2RatePrice {
    return LodgifyApiRatesModelsV2RatePriceToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2RatePriceToJSONTyped(value?: LodgifyApiRatesModelsV2RatePrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rate_type': value['rateType'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

