/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto {
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
     */
    feeType?: LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFeeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto
     */
    roomRateType?: LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoRoomRateTypeEnum;
}


/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFeeTypeEnum = {
    Cleaning: 'Cleaning',
    Miscellaneous: 'Miscellaneous',
    DamageProtectionInsurance: 'DamageProtectionInsurance',
    ManagementFee: 'ManagementFee',
    ServiceFee: 'ServiceFee',
    Wood: 'Wood',
    DrinkingWater: 'DrinkingWater',
    WaterCraftMooring: 'WaterCraftMooring',
    WaterCraft: 'WaterCraft',
    Water: 'Water',
    Vehicle: 'Vehicle',
    FoodUtensils: 'FoodUtensils',
    UtensilsCleaning: 'UtensilsCleaning',
    Transportation: 'Transportation',
    Tour: 'Tour',
    Toiletries: 'Toiletries',
    Spa: 'Spa',
    Resort: 'Resort',
    Rent: 'Rent',
    Parking: 'Parking',
    Phone: 'Phone',
    OnSitePaymentMethod: 'OnSitePaymentMethod',
    Oil: 'Oil',
    LinensBed: 'LinensBed',
    LinensBath: 'LinensBath',
    Linens: 'Linens',
    Laundry: 'Laundry',
    Labor: 'Labor',
    Internet: 'Internet',
    TravelInsurance: 'TravelInsurance',
    HotTub: 'HotTub',
    HighChair: 'HighChair',
    Heating: 'Heating',
    Gas: 'Gas',
    Gardening: 'Gardening',
    Food: 'Food',
    Equipment: 'Equipment',
    Electricity: 'Electricity',
    Concierge: 'Concierge',
    PoolHeating: 'PoolHeating',
    Pool: 'Pool',
    Class: 'Class',
    BabyBed: 'BabyBed',
    PropertyAssociation: 'PropertyAssociation',
    AirConditioning: 'AirConditioning',
    AdditionalBed: 'AdditionalBed',
    PetFee: 'PetFee',
    ServiceCharge: 'ServiceCharge',
    GratuityFee: 'GratuityFee',
    DamageWaiver: 'DamageWaiver',
    Community: 'Community'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFeeTypeEnum = typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFeeTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFeeTypeEnum];

/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoRoomRateTypeEnum = {
    Stay: 'Stay',
    ShortStayPremium: 'ShortStayPremium'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoRoomRateTypeEnum = typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoRoomRateTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoRoomRateTypeEnum];


/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'feeType': json['fee_type'] == null ? undefined : json['fee_type'],
        'roomRateType': json['room_rate_type'] == null ? undefined : json['room_rate_type'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteQuotePriceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'description': value['description'],
        'amount': value['amount'],
        'fee_type': value['feeType'],
        'room_rate_type': value['roomRateType'],
    };
}

