/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInner } from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInner';
import {
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInner';

/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto {
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
     */
    roomTypeId?: number;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
     */
    people?: number;
    /**
     * 
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
     */
    priceTypes?: Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInner> | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto
     */
    subtotal?: number;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roomTypeId': json['room_type_id'] == null ? undefined : json['room_type_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'people': json['people'] == null ? undefined : json['people'],
        'priceTypes': json['price_types'] == null ? undefined : ((json['price_types'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerFromJSON)),
        'subtotal': json['subtotal'] == null ? undefined : json['subtotal'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteQuoteRoomTypeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'room_type_id': value['roomTypeId'],
        'name': value['name'],
        'people': value['people'],
        'price_types': value['priceTypes'] == null ? undefined : ((value['priceTypes'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerToJSON)),
        'subtotal': value['subtotal'],
    };
}

