/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetExternalBookingsAsync200ResponseExternalBookingsInner } from './GetExternalBookingsAsync200ResponseExternalBookingsInner';
import {
    GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSON,
    GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSONTyped,
    GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSON,
    GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSONTyped,
} from './GetExternalBookingsAsync200ResponseExternalBookingsInner';

/**
 * External bookings result
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto {
    /**
     * List of external bookings
     * @type {Array<GetExternalBookingsAsync200ResponseExternalBookingsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto
     */
    externalBookings?: Array<GetExternalBookingsAsync200ResponseExternalBookingsInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'externalBookings': json['external_bookings'] == null ? undefined : ((json['external_bookings'] as Array<any>).map(GetExternalBookingsAsync200ResponseExternalBookingsInnerFromJSON)),
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsExternalBookingListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_bookings': value['externalBookings'] == null ? undefined : ((value['externalBookings'] as Array<any>).map(GetExternalBookingsAsync200ResponseExternalBookingsInnerToJSON)),
    };
}

