/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object used to checkout a booking
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto {
    /**
     * Time of the checkout (in the property's timezone). Use format HH:mm:ss
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto
     */
    time: string;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto {
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingCheckOutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
    };
}

