/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateKeyCodesRequestRoomsInner } from './UpdateKeyCodesRequestRoomsInner';
import {
    UpdateKeyCodesRequestRoomsInnerFromJSON,
    UpdateKeyCodesRequestRoomsInnerFromJSONTyped,
    UpdateKeyCodesRequestRoomsInnerToJSON,
    UpdateKeyCodesRequestRoomsInnerToJSONTyped,
} from './UpdateKeyCodesRequestRoomsInner';

/**
 * Represents a Booking with the list of room types and keycodes to access to the properties rented.
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto {
    /**
     * List of room types of the booking.
     * @type {Array<UpdateKeyCodesRequestRoomsInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto
     */
    rooms?: Array<UpdateKeyCodesRequestRoomsInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rooms': json['rooms'] == null ? undefined : ((json['rooms'] as Array<any>).map(UpdateKeyCodesRequestRoomsInnerFromJSON)),
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsBookingKeyCodeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rooms': value['rooms'] == null ? undefined : ((value['rooms'] as Array<any>).map(UpdateKeyCodesRequestRoomsInnerToJSON)),
    };
}

