/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteFeeType = {
    Cleaning: 'Cleaning',
    Miscellaneous: 'Miscellaneous',
    DamageProtectionInsurance: 'DamageProtectionInsurance',
    ManagementFee: 'ManagementFee',
    ServiceFee: 'ServiceFee',
    Wood: 'Wood',
    DrinkingWater: 'DrinkingWater',
    WaterCraftMooring: 'WaterCraftMooring',
    WaterCraft: 'WaterCraft',
    Water: 'Water',
    Vehicle: 'Vehicle',
    FoodUtensils: 'FoodUtensils',
    UtensilsCleaning: 'UtensilsCleaning',
    Transportation: 'Transportation',
    Tour: 'Tour',
    Toiletries: 'Toiletries',
    Spa: 'Spa',
    Resort: 'Resort',
    Rent: 'Rent',
    Parking: 'Parking',
    Phone: 'Phone',
    OnSitePaymentMethod: 'OnSitePaymentMethod',
    Oil: 'Oil',
    LinensBed: 'LinensBed',
    LinensBath: 'LinensBath',
    Linens: 'Linens',
    Laundry: 'Laundry',
    Labor: 'Labor',
    Internet: 'Internet',
    TravelInsurance: 'TravelInsurance',
    HotTub: 'HotTub',
    HighChair: 'HighChair',
    Heating: 'Heating',
    Gas: 'Gas',
    Gardening: 'Gardening',
    Food: 'Food',
    Equipment: 'Equipment',
    Electricity: 'Electricity',
    Concierge: 'Concierge',
    PoolHeating: 'PoolHeating',
    Pool: 'Pool',
    Class: 'Class',
    BabyBed: 'BabyBed',
    PropertyAssociation: 'PropertyAssociation',
    AirConditioning: 'AirConditioning',
    AdditionalBed: 'AdditionalBed',
    PetFee: 'PetFee',
    ServiceCharge: 'ServiceCharge',
    GratuityFee: 'GratuityFee',
    DamageWaiver: 'DamageWaiver',
    Community: 'Community'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteFeeType = typeof LodgifyApiPublicReservationsModelsV2QuoteFeeType[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteFeeType];


export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteFeeType(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2QuoteFeeType) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2QuoteFeeType, key)) {
            if (LodgifyApiPublicReservationsModelsV2QuoteFeeType[key as keyof typeof LodgifyApiPublicReservationsModelsV2QuoteFeeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2QuoteFeeTypeFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteFeeType {
    return LodgifyApiPublicReservationsModelsV2QuoteFeeTypeFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteFeeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteFeeType {
    return json as LodgifyApiPublicReservationsModelsV2QuoteFeeType;
}

export function LodgifyApiPublicReservationsModelsV2QuoteFeeTypeToJSON(value?: LodgifyApiPublicReservationsModelsV2QuoteFeeType | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2QuoteFeeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteFeeType {
    return value as LodgifyApiPublicReservationsModelsV2QuoteFeeType;
}

