/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAllPropertiesAsync200ResponseItemsInner } from './GetAllPropertiesAsync200ResponseItemsInner';
import {
    GetAllPropertiesAsync200ResponseItemsInnerFromJSON,
    GetAllPropertiesAsync200ResponseItemsInnerFromJSONTyped,
    GetAllPropertiesAsync200ResponseItemsInnerToJSON,
    GetAllPropertiesAsync200ResponseItemsInnerToJSONTyped,
} from './GetAllPropertiesAsync200ResponseItemsInner';

/**
 * Paged list of Properties Object.
 * @export
 * @interface LodgifyApiPropertiesModelsV2PropertyListDto
 */
export interface LodgifyApiPropertiesModelsV2PropertyListDto {
    /**
     * Total number of items available. Only returned if includeCount = true
     * @type {number}
     * @memberof LodgifyApiPropertiesModelsV2PropertyListDto
     */
    count?: number | null;
    /**
     * List of properties for current page
     * @type {Array<GetAllPropertiesAsync200ResponseItemsInner>}
     * @memberof LodgifyApiPropertiesModelsV2PropertyListDto
     */
    items?: Array<GetAllPropertiesAsync200ResponseItemsInner> | null;
}

/**
 * Check if a given object implements the LodgifyApiPropertiesModelsV2PropertyListDto interface.
 */
export function instanceOfLodgifyApiPropertiesModelsV2PropertyListDto(value: object): value is LodgifyApiPropertiesModelsV2PropertyListDto {
    return true;
}

export function LodgifyApiPropertiesModelsV2PropertyListDtoFromJSON(json: any): LodgifyApiPropertiesModelsV2PropertyListDto {
    return LodgifyApiPropertiesModelsV2PropertyListDtoFromJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2PropertyListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPropertiesModelsV2PropertyListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerFromJSON)),
    };
}

export function LodgifyApiPropertiesModelsV2PropertyListDtoToJSON(json: any): LodgifyApiPropertiesModelsV2PropertyListDto {
    return LodgifyApiPropertiesModelsV2PropertyListDtoToJSONTyped(json, false);
}

export function LodgifyApiPropertiesModelsV2PropertyListDtoToJSONTyped(value?: LodgifyApiPropertiesModelsV2PropertyListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(GetAllPropertiesAsync200ResponseItemsInnerToJSON)),
    };
}

