/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum = {
    Upcoming: 'Upcoming',
    Current: 'Current',
    Historic: 'Historic',
    All: 'All',
    ArrivalDate: 'ArrivalDate',
    DepartureDate: 'DepartureDate'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsBookingsStayFilterEnum;
}

