/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Transaction scheduled in the Quote
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
 */
export interface LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto {
    /**
     * Id of the scheduled item
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
     */
    id?: number;
    /**
     * Type of scheduled transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
     */
    type?: LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoTypeEnum;
    /**
     * Status of a scheduled transaction
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
     */
    status?: LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
     */
    amount?: object;
    /**
     * The date the schedule item will be due at. 
     * Null means that the date will be the date of the booking agreement.
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto
     */
    dueAt?: string | null;
}


/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoTypeEnum = {
    PrePayment: 'PrePayment',
    InterimPayment: 'InterimPayment',
    BalancePayment: 'BalancePayment',
    PrecedingPayment: 'PrecedingPayment',
    Cancellation: 'Cancellation',
    DamageDepositAuthorization: 'DamageDepositAuthorization',
    DamageDepositVoid: 'DamageDepositVoid',
    SecurityDepositCharge: 'SecurityDepositCharge',
    SecurityDepositRefund: 'SecurityDepositRefund'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoTypeEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoTypeEnum];

/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoStatusEnum = {
    Scheduled: 'Scheduled',
    Overdue: 'Overdue',
    Pending: 'Pending',
    Aborted: 'Aborted',
    Paid: 'Paid',
    Refunded: 'Refunded',
    Authorized: 'Authorized',
    Voided: 'Voided',
    Captured: 'Captured',
    Shown: 'Shown'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoStatusEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoStatusEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoStatusEnum];


/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto(value: object): value is LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'dueAt': json['due_at'] == null ? undefined : json['due_at'],
    };
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto {
    return LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'amount': value['amount'],
        'due_at': value['dueAt'],
    };
}

