/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Guest breakdown
 * @export
 * @interface LodgifyApiPublicReservationsModelsV12GuestBreakdownDto
 */
export interface LodgifyApiPublicReservationsModelsV12GuestBreakdownDto {
    /**
     * Number of adults
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV12GuestBreakdownDto
     */
    adults?: number;
    /**
     * Number of children
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV12GuestBreakdownDto
     */
    children?: number;
    /**
     * Number of infants
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV12GuestBreakdownDto
     */
    infants?: number;
    /**
     * Number of pets
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV12GuestBreakdownDto
     */
    pets?: number;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV12GuestBreakdownDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV12GuestBreakdownDto(value: object): value is LodgifyApiPublicReservationsModelsV12GuestBreakdownDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV12GuestBreakdownDto {
    return LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV12GuestBreakdownDto {
    if (json == null) {
        return json;
    }
    return {
        
        'adults': json['adults'] == null ? undefined : json['adults'],
        'children': json['children'] == null ? undefined : json['children'],
        'infants': json['infants'] == null ? undefined : json['infants'],
        'pets': json['pets'] == null ? undefined : json['pets'],
    };
}

export function LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV12GuestBreakdownDto {
    return LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV12GuestBreakdownDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV12GuestBreakdownDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adults': value['adults'],
        'children': value['children'],
        'infants': value['infants'],
        'pets': value['pets'],
    };
}

