/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseCalendarItemsInner } from './RatesCalendarV2200ResponseCalendarItemsInner';
import {
    RatesCalendarV2200ResponseCalendarItemsInnerFromJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerFromJSONTyped,
    RatesCalendarV2200ResponseCalendarItemsInnerToJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerToJSONTyped,
} from './RatesCalendarV2200ResponseCalendarItemsInner';
import type { RatesCalendarV2200ResponseRateSettings } from './RatesCalendarV2200ResponseRateSettings';
import {
    RatesCalendarV2200ResponseRateSettingsFromJSON,
    RatesCalendarV2200ResponseRateSettingsFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsToJSON,
    RatesCalendarV2200ResponseRateSettingsToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettings';

/**
 * Defines the daily rates calendar and rate settings for a property
 * @export
 * @interface LodgifyApiRatesModelsV2CalendarResponse
 */
export interface LodgifyApiRatesModelsV2CalendarResponse {
    /**
     * Calendar items
     * @type {Array<RatesCalendarV2200ResponseCalendarItemsInner>}
     * @memberof LodgifyApiRatesModelsV2CalendarResponse
     */
    calendarItems?: Array<RatesCalendarV2200ResponseCalendarItemsInner> | null;
    /**
     * 
     * @type {RatesCalendarV2200ResponseRateSettings}
     * @memberof LodgifyApiRatesModelsV2CalendarResponse
     */
    rateSettings?: RatesCalendarV2200ResponseRateSettings;
}

/**
 * Check if a given object implements the LodgifyApiRatesModelsV2CalendarResponse interface.
 */
export function instanceOfLodgifyApiRatesModelsV2CalendarResponse(value: object): value is LodgifyApiRatesModelsV2CalendarResponse {
    return true;
}

export function LodgifyApiRatesModelsV2CalendarResponseFromJSON(json: any): LodgifyApiRatesModelsV2CalendarResponse {
    return LodgifyApiRatesModelsV2CalendarResponseFromJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiRatesModelsV2CalendarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarItems': json['calendar_items'] == null ? undefined : ((json['calendar_items'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerFromJSON)),
        'rateSettings': json['rate_settings'] == null ? undefined : RatesCalendarV2200ResponseRateSettingsFromJSON(json['rate_settings']),
    };
}

export function LodgifyApiRatesModelsV2CalendarResponseToJSON(json: any): LodgifyApiRatesModelsV2CalendarResponse {
    return LodgifyApiRatesModelsV2CalendarResponseToJSONTyped(json, false);
}

export function LodgifyApiRatesModelsV2CalendarResponseToJSONTyped(value?: LodgifyApiRatesModelsV2CalendarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar_items': value['calendarItems'] == null ? undefined : ((value['calendarItems'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerToJSON)),
        'rate_settings': RatesCalendarV2200ResponseRateSettingsToJSON(value['rateSettings']),
    };
}

