/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteRoomRateType = {
    Stay: 'Stay',
    ShortStayPremium: 'ShortStayPremium'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteRoomRateType = typeof LodgifyApiPublicReservationsModelsV2QuoteRoomRateType[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteRoomRateType];


export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteRoomRateType(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2QuoteRoomRateType) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2QuoteRoomRateType, key)) {
            if (LodgifyApiPublicReservationsModelsV2QuoteRoomRateType[key as keyof typeof LodgifyApiPublicReservationsModelsV2QuoteRoomRateType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomRateTypeFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteRoomRateType {
    return LodgifyApiPublicReservationsModelsV2QuoteRoomRateTypeFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomRateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteRoomRateType {
    return json as LodgifyApiPublicReservationsModelsV2QuoteRoomRateType;
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomRateTypeToJSON(value?: LodgifyApiPublicReservationsModelsV2QuoteRoomRateType | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2QuoteRoomRateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteRoomRateType {
    return value as LodgifyApiPublicReservationsModelsV2QuoteRoomRateType;
}

