/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto
 */
export interface LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto {
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto
     */
    status?: string | null;
}

/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto(value: object): value is LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto {
    return LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2AvailabilityBookingAvailabilityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

