/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner } from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner';
import {
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSONTyped,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSON,
    V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSONTyped,
} from './V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner';

/**
 * 
 * @export
 * @interface LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
 */
export interface LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto {
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
     */
    type?: LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
     */
    isNegative?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
     */
    description?: string | null;
    /**
     * 
     * @type {Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner>}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
     */
    prices?: Array<V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInner> | null;
    /**
     * 
     * @type {number}
     * @memberof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto
     */
    subtotal?: number;
}


/**
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoTypeEnum = {
    RoomRate: 'RoomRate',
    Promotion: 'Promotion',
    Fee: 'Fee',
    AddOn: 'AddOn',
    Tax: 'Tax',
    Other: 'Other'
} as const;
export type LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoTypeEnum = typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoTypeEnum[keyof typeof LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoTypeEnum];


/**
 * Check if a given object implements the LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto interface.
 */
export function instanceOfLodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto(value: object): value is LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto {
    return true;
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoFromJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'isNegative': json['is_negative'] == null ? undefined : json['is_negative'],
        'description': json['description'] == null ? undefined : json['description'],
        'prices': json['prices'] == null ? undefined : ((json['prices'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerFromJSON)),
        'subtotal': json['subtotal'] == null ? undefined : json['subtotal'],
    };
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoToJSON(json: any): LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto {
    return LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoToJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDtoToJSONTyped(value?: LodgifyApiPublicReservationsModelsV2QuoteQuotePriceTypeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'is_negative': value['isNegative'],
        'description': value['description'],
        'prices': value['prices'] == null ? undefined : ((value['prices'] as Array<any>).map(V2QuotePropertyIdGet200ResponseInnerRoomTypesInnerPriceTypesInnerPricesInnerToJSON)),
        'subtotal': value['subtotal'],
    };
}

