/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a scheduled transaction
 * @export
 */
export const LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum = {
    Scheduled: 'Scheduled',
    Overdue: 'Overdue',
    Pending: 'Pending',
    Aborted: 'Aborted',
    Paid: 'Paid',
    Refunded: 'Refunded',
    Authorized: 'Authorized',
    Voided: 'Voided',
    Captured: 'Captured',
    Shown: 'Shown'
} as const;
export type LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum = typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum[keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum];


export function instanceOfLodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum(value: any): boolean {
    for (const key in LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum, key)) {
            if (LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum[key as keyof typeof LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnumFromJSON(json: any): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum {
    return LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnumFromJSONTyped(json, false);
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum {
    return json as LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnumToJSON(value?: LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum | null): any {
    return value as any;
}

export function LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum {
    return value as LodgifyApiPublicReservationsModelsV2ReservationsQuotesScheduledTransactionStatusEnum;
}

