/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseCalendarItemsInnerPricesInner } from './RatesCalendarV2200ResponseCalendarItemsInnerPricesInner';
import {
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSONTyped,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSON,
    RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseCalendarItemsInnerPricesInner';

/**
 * 
 * @export
 * @interface RatesCalendarV2200ResponseCalendarItemsInner
 */
export interface RatesCalendarV2200ResponseCalendarItemsInner {
    /**
     * Represents the DateTime for the calendar item
     * @type {string}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInner
     */
    date?: string | null;
    /**
     * Indicates if the calendar item is the default rate
     * @type {boolean}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInner
     */
    isDefault?: boolean;
    /**
     * List of prices for the calendar item
     * @type {Array<RatesCalendarV2200ResponseCalendarItemsInnerPricesInner>}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInner
     */
    prices?: Array<RatesCalendarV2200ResponseCalendarItemsInnerPricesInner> | null;
}

/**
 * Check if a given object implements the RatesCalendarV2200ResponseCalendarItemsInner interface.
 */
export function instanceOfRatesCalendarV2200ResponseCalendarItemsInner(value: object): value is RatesCalendarV2200ResponseCalendarItemsInner {
    return true;
}

export function RatesCalendarV2200ResponseCalendarItemsInnerFromJSON(json: any): RatesCalendarV2200ResponseCalendarItemsInner {
    return RatesCalendarV2200ResponseCalendarItemsInnerFromJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseCalendarItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesCalendarV2200ResponseCalendarItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'prices': json['prices'] == null ? undefined : ((json['prices'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSON)),
    };
}

export function RatesCalendarV2200ResponseCalendarItemsInnerToJSON(json: any): RatesCalendarV2200ResponseCalendarItemsInner {
    return RatesCalendarV2200ResponseCalendarItemsInnerToJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseCalendarItemsInnerToJSONTyped(value?: RatesCalendarV2200ResponseCalendarItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'is_default': value['isDefault'],
        'prices': value['prices'] == null ? undefined : ((value['prices'] as Array<any>).map(RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSON)),
    };
}

