/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesCalendarV2200ResponseRateSettingsPromotionsInner } from './RatesCalendarV2200ResponseRateSettingsPromotionsInner';
import {
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerFromJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerToJSON,
    RatesCalendarV2200ResponseRateSettingsPromotionsInnerToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsPromotionsInner';
import type { RatesCalendarV2200ResponseRateSettingsFeesInner } from './RatesCalendarV2200ResponseRateSettingsFeesInner';
import {
    RatesCalendarV2200ResponseRateSettingsFeesInnerFromJSON,
    RatesCalendarV2200ResponseRateSettingsFeesInnerFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsFeesInnerToJSON,
    RatesCalendarV2200ResponseRateSettingsFeesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsFeesInner';
import type { RatesCalendarV2200ResponseRateSettingsTaxesInner } from './RatesCalendarV2200ResponseRateSettingsTaxesInner';
import {
    RatesCalendarV2200ResponseRateSettingsTaxesInnerFromJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerFromJSONTyped,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerToJSON,
    RatesCalendarV2200ResponseRateSettingsTaxesInnerToJSONTyped,
} from './RatesCalendarV2200ResponseRateSettingsTaxesInner';

/**
 * 
 * @export
 * @interface RatesCalendarV2200ResponseRateSettings
 */
export interface RatesCalendarV2200ResponseRateSettings {
    /**
     * 
     * @type {string}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    bookability?: RatesCalendarV2200ResponseRateSettingsBookabilityEnum;
    /**
     * If present, minimum hour allowed to check in
     * -1: Flexible, 0-23: Hour of day
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    checkInHour?: number | null;
    /**
     * If present, maximum hour allowed to check out
     * -1: Flexible, 0-23: Hour of day
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    checkOutHour?: number | null;
    /**
     * Limits how many days in advance guests can book.
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    bookingWindowDays?: number;
    /**
     * Specifies how many days in advance a guest can make a reservation
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    advanceNoticeDays?: number;
    /**
     * Specifies how many hours in advance a guest can make a reservation
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    advanceNoticeHours?: number | null;
    /**
     * Indicates the time between bookings when reservations are not allowed
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    preparationTimeDays?: number;
    /**
     * Currency code
     * @type {string}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    currencyCode?: string | null;
    /**
     * Vat amount
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    vat?: number;
    /**
     * Indicates if the price is vat exclusive
     * @type {boolean}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    isVatExclusive?: boolean;
    /**
     * List of fees applied to this room rate
     * @type {Array<RatesCalendarV2200ResponseRateSettingsFeesInner>}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    fees?: Array<RatesCalendarV2200ResponseRateSettingsFeesInner> | null;
    /**
     * List of taxes applied to this room rate
     * @type {Array<RatesCalendarV2200ResponseRateSettingsTaxesInner>}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    taxes?: Array<RatesCalendarV2200ResponseRateSettingsTaxesInner> | null;
    /**
     * List of promotions applied to this room rate
     * @type {Array<RatesCalendarV2200ResponseRateSettingsPromotionsInner>}
     * @memberof RatesCalendarV2200ResponseRateSettings
     */
    promotions?: Array<RatesCalendarV2200ResponseRateSettingsPromotionsInner> | null;
}


/**
 * @export
 */
export const RatesCalendarV2200ResponseRateSettingsBookabilityEnum = {
    InstantBooking: 'InstantBooking',
    BookingRequest: 'BookingRequest',
    EnquiryOnly: 'EnquiryOnly'
} as const;
export type RatesCalendarV2200ResponseRateSettingsBookabilityEnum = typeof RatesCalendarV2200ResponseRateSettingsBookabilityEnum[keyof typeof RatesCalendarV2200ResponseRateSettingsBookabilityEnum];


/**
 * Check if a given object implements the RatesCalendarV2200ResponseRateSettings interface.
 */
export function instanceOfRatesCalendarV2200ResponseRateSettings(value: object): value is RatesCalendarV2200ResponseRateSettings {
    return true;
}

export function RatesCalendarV2200ResponseRateSettingsFromJSON(json: any): RatesCalendarV2200ResponseRateSettings {
    return RatesCalendarV2200ResponseRateSettingsFromJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesCalendarV2200ResponseRateSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'bookability': json['bookability'] == null ? undefined : json['bookability'],
        'checkInHour': json['check_in_hour'] == null ? undefined : json['check_in_hour'],
        'checkOutHour': json['check_out_hour'] == null ? undefined : json['check_out_hour'],
        'bookingWindowDays': json['booking_window_days'] == null ? undefined : json['booking_window_days'],
        'advanceNoticeDays': json['advance_notice_days'] == null ? undefined : json['advance_notice_days'],
        'advanceNoticeHours': json['advance_notice_hours'] == null ? undefined : json['advance_notice_hours'],
        'preparationTimeDays': json['preparation_time_days'] == null ? undefined : json['preparation_time_days'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'isVatExclusive': json['is_vat_exclusive'] == null ? undefined : json['is_vat_exclusive'],
        'fees': json['fees'] == null ? undefined : ((json['fees'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsFeesInnerFromJSON)),
        'taxes': json['taxes'] == null ? undefined : ((json['taxes'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsTaxesInnerFromJSON)),
        'promotions': json['promotions'] == null ? undefined : ((json['promotions'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerFromJSON)),
    };
}

export function RatesCalendarV2200ResponseRateSettingsToJSON(json: any): RatesCalendarV2200ResponseRateSettings {
    return RatesCalendarV2200ResponseRateSettingsToJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsToJSONTyped(value?: RatesCalendarV2200ResponseRateSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookability': value['bookability'],
        'check_in_hour': value['checkInHour'],
        'check_out_hour': value['checkOutHour'],
        'booking_window_days': value['bookingWindowDays'],
        'advance_notice_days': value['advanceNoticeDays'],
        'advance_notice_hours': value['advanceNoticeHours'],
        'preparation_time_days': value['preparationTimeDays'],
        'currency_code': value['currencyCode'],
        'vat': value['vat'],
        'is_vat_exclusive': value['isVatExclusive'],
        'fees': value['fees'] == null ? undefined : ((value['fees'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsFeesInnerToJSON)),
        'taxes': value['taxes'] == null ? undefined : ((value['taxes'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsTaxesInnerToJSON)),
        'promotions': value['promotions'] == null ? undefined : ((value['promotions'] as Array<any>).map(RatesCalendarV2200ResponseRateSettingsPromotionsInnerToJSON)),
    };
}

