/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
 */
export interface RatesCalendarV2200ResponseCalendarItemsInnerPricesInner {
    /**
     * Minimum days to stay
     * @type {number}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
     */
    minStay?: number;
    /**
     * Maximum days to stay
     * @type {number}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
     */
    maxStay?: number;
    /**
     * 
     * @type {object}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
     */
    pricePerDay?: object;
    /**
     * 
     * @type {object}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
     */
    pricePerAdditionalGuest?: object;
    /**
     * Indicates the number of people from which an extra charge is charged
     * @type {number}
     * @memberof RatesCalendarV2200ResponseCalendarItemsInnerPricesInner
     */
    additionalGuestsStartsFrom?: number;
}

/**
 * Check if a given object implements the RatesCalendarV2200ResponseCalendarItemsInnerPricesInner interface.
 */
export function instanceOfRatesCalendarV2200ResponseCalendarItemsInnerPricesInner(value: object): value is RatesCalendarV2200ResponseCalendarItemsInnerPricesInner {
    return true;
}

export function RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSON(json: any): RatesCalendarV2200ResponseCalendarItemsInnerPricesInner {
    return RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesCalendarV2200ResponseCalendarItemsInnerPricesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'minStay': json['min_stay'] == null ? undefined : json['min_stay'],
        'maxStay': json['max_stay'] == null ? undefined : json['max_stay'],
        'pricePerDay': json['price_per_day'] == null ? undefined : json['price_per_day'],
        'pricePerAdditionalGuest': json['price_per_additional_guest'] == null ? undefined : json['price_per_additional_guest'],
        'additionalGuestsStartsFrom': json['additional_guests_starts_from'] == null ? undefined : json['additional_guests_starts_from'],
    };
}

export function RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSON(json: any): RatesCalendarV2200ResponseCalendarItemsInnerPricesInner {
    return RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseCalendarItemsInnerPricesInnerToJSONTyped(value?: RatesCalendarV2200ResponseCalendarItemsInnerPricesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_stay': value['minStay'],
        'max_stay': value['maxStay'],
        'price_per_day': value['pricePerDay'],
        'price_per_additional_guest': value['pricePerAdditionalGuest'],
        'additional_guests_starts_from': value['additionalGuestsStartsFrom'],
    };
}

