/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rate price
 * @export
 * @interface RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice
 */
export interface RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice {
    /**
     * Rate type, equals "Fixed" for a fixed amount price, "Percentage" for a percentage price
     * @type {string}
     * @memberof RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice
     */
    rateType?: string | null;
    /**
     * 
     * @type {object}
     * @memberof RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice
     */
    amount?: object;
    /**
     * Price value percentage
     * @type {number}
     * @memberof RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice
     */
    percentage?: number | null;
}

/**
 * Check if a given object implements the RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice interface.
 */
export function instanceOfRatesCalendarV2200ResponseRateSettingsTaxesInnerPrice(value: object): value is RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice {
    return true;
}

export function RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSON(json: any): RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice {
    return RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'rateType': json['rate_type'] == null ? undefined : json['rate_type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSON(json: any): RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice {
    return RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSONTyped(json, false);
}

export function RatesCalendarV2200ResponseRateSettingsTaxesInnerPriceToJSONTyped(value?: RatesCalendarV2200ResponseRateSettingsTaxesInnerPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rate_type': value['rateType'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

