/* tslint:disable */
/* eslint-disable */
/**
 * Lodgify Public API v2
 * API documentation for Lodgify Public API v2
 *
 * The version of the OpenAPI document: v2
 * Contact: development@lodgify.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2QuotePropertyIdGet200ResponseInnerAddOnsInner
 */
export interface V2QuotePropertyIdGet200ResponseInnerAddOnsInner {
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerAddOnsInner
     */
    addOnId?: number;
    /**
     * 
     * @type {string}
     * @memberof V2QuotePropertyIdGet200ResponseInnerAddOnsInner
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerAddOnsInner
     */
    units?: number | null;
    /**
     * 
     * @type {number}
     * @memberof V2QuotePropertyIdGet200ResponseInnerAddOnsInner
     */
    amount?: number;
}

/**
 * Check if a given object implements the V2QuotePropertyIdGet200ResponseInnerAddOnsInner interface.
 */
export function instanceOfV2QuotePropertyIdGet200ResponseInnerAddOnsInner(value: object): value is V2QuotePropertyIdGet200ResponseInnerAddOnsInner {
    return true;
}

export function V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSON(json: any): V2QuotePropertyIdGet200ResponseInnerAddOnsInner {
    return V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerAddOnsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2QuotePropertyIdGet200ResponseInnerAddOnsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'addOnId': json['add_on_id'] == null ? undefined : json['add_on_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'units': json['units'] == null ? undefined : json['units'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSON(json: any): V2QuotePropertyIdGet200ResponseInnerAddOnsInner {
    return V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSONTyped(json, false);
}

export function V2QuotePropertyIdGet200ResponseInnerAddOnsInnerToJSONTyped(value?: V2QuotePropertyIdGet200ResponseInnerAddOnsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'add_on_id': value['addOnId'],
        'name': value['name'],
        'units': value['units'],
        'amount': value['amount'],
    };
}

