name: Scheduled Netlify Rebuild

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: # allows manual trigger too

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Netlify Build Hook
        run: curl -X POST https://api.netlify.com/build_hooks/6857bf63fc1bc8e7721396ca
